"""Bangla copy for the focused planning and forecast experience."""

FEEDBACK_BANGLA = {
    "Plan your spending. Keep recurring payments on time.": "খরচের পরিকল্পনা করুন। নিয়মিত পেমেন্ট সময়মতো দিন।",
    "Your two planning tasks": "আপনার পরিকল্পনার দুটি কাজ",
    "1 · Plan this week": "১ · এই সপ্তাহের পরিকল্পনা",
    "2 · Pay on time": "২ · সময়মতো পেমেন্ট",
    "Set aside upcoming commitments before planning everyday spending.": "দৈনন্দিন খরচের পরিকল্পনার আগে আসন্ন পেমেন্টের টাকা আলাদা রাখুন।",
    "Left after recorded payments due in the next 7 days and overdue items.": "আগামী ৭ দিনের নির্ধারিত ও বকেয়া পেমেন্ট বাদ দেওয়ার পর অবশিষ্ট।",
    "Recurring payments": "নিয়মিত পেমেন্ট",
    "Plan bills, recharge and family transfers. Review due dates and payment failures.": "বিল, রিচার্জ ও পরিবারের জন্য টাকা পাঠানোর পরিকল্পনা করুন। নির্ধারিত তারিখ ও ব্যর্থ পেমেন্ট দেখুন।",
    "due soon": "শিগগির পরিশোধযোগ্য",
    "More wallet services": "আরও ওয়ালেট সেবা",
    "Pilot & Feedback": "পাইলট ও মতামত",
    "Planning research pilot": "পরিকল্পনা গবেষণার পাইলট",
    "Two customer problems": "গ্রাহকের দুটি সমস্যা",
    "Help us test financial planning and recurring payment management with observed task outcomes.": "কাজের ফল দেখে আর্থিক পরিকল্পনা ও নিয়মিত পেমেন্ট ব্যবস্থাপনা পরীক্ষা করতে সাহায্য করুন।",
    "What we are testing": "আমরা যা পরীক্ষা করছি",
    "Does a cash-flow forecast alongside the recorded commitment estimate help people complete a planning review? Participants receive either the existing commitment estimate (control) or the estimate plus the forecast (treatment). Auto Pay and the planning acknowledgement are available to both groups.": "নির্ধারিত পেমেন্টের হিসাবের সঙ্গে খরচের পূর্বাভাস দিলে পরিকল্পনা পর্যালোচনা সহজ হয় কি না আমরা পরীক্ষা করছি। একটি দল শুধু বর্তমান হিসাব দেখবে, অন্য দল হিসাবের সঙ্গে পূর্বাভাসও দেখবে। দুটি দলই অটো পে ও পরিকল্পনা পর্যালোচনা ব্যবহার করতে পারবে।",
    "Participation is optional. We record study group, page exposure, activity days, planning acknowledgements, successful simulated transactions, scheduled payment outcomes and your research answers. Your study group and session source stay fixed. Your own observations appear here; only the local study operator can export aggregate cohort totals.": "অংশগ্রহণ ঐচ্ছিক। আপনার গবেষণার দল, পেজ দেখা, ব্যবহারের দিন, পরিকল্পনা পর্যালোচনা, সফল ডেমো লেনদেন, নির্ধারিত পেমেন্টের ফল ও গবেষণার উত্তর সংরক্ষণ করা হবে। দল ও সেশনের উৎস স্থির থাকবে। এখানে শুধু আপনার তথ্য দেখাবে; গবেষণার পরিচালক দলগুলোর মোট ফল রপ্তানি করতে পারবেন।",
    "You can withdraw to stop collection. Existing observations remain in the study denominators, including withdrawals, so the comparison does not hide dropouts. Do not include PINs, account numbers, contact details or other sensitive information in comments.": "অংশগ্রহণ বন্ধ করলে নতুন তথ্য সংগ্রহ বন্ধ হবে। আগে দেওয়া তথ্য ও সরে যাওয়ার তথ্য গবেষণার হিসাবে থাকবে, যাতে তুলনায় বাদ পড়া অংশগ্রহণকারী আড়াল না হয়। মন্তব্যে পিন, অ্যাকাউন্ট নম্বর, যোগাযোগের তথ্য বা অন্য সংবেদনশীল তথ্য দেবেন না।",
    "If choosing real research, I am a real recruited research participant. Operator verification is required before these observations enter real research totals.": "প্রকৃত গবেষণা বেছে নিলে আমি নিয়োগ করা একজন প্রকৃত অংশগ্রহণকারী। গবেষণার মোট হিসাবে যুক্ত করার আগে পরিচালকের যাচাই দরকার।",
    "I have read this study description and consent to the observations above.": "আমি গবেষণার বিবরণ পড়েছি এবং উপরের তথ্য সংগ্রহে সম্মতি দিচ্ছি।",
    "Join with consent": "সম্মতি দিয়ে যোগ দিন",
    "Session source": "সেশনের উৎস",
    "Demo / synthetic session": "ডেমো / কৃত্রিম তথ্যের সেশন",
    "Real participant research session": "প্রকৃত অংশগ্রহণকারীর গবেষণার সেশন",
    "Join planning pilot": "পরিকল্পনার পাইলটে যোগ দিন",
    "Your participation": "আপনার অংশগ্রহণ",
    "Review my plan": "আমার পরিকল্পনা দেখুন",
    "Set up a recurring payment": "নিয়মিত পেমেন্ট তৈরি করুন",
    "Withdraw from pilot": "পাইলট থেকে সরে যান",
    "Your observed study outcomes": "গবেষণায় আপনার কাজের ফল",
    "Outcome": "ফল",
    "Observed count / denominator": "পর্যবেক্ষণের সংখ্যা / মোট যোগ্য সংখ্যা",
    "This page contains your account only. Cohort comparison requires the operator's aggregate report. “Unavailable” means there is no eligible observation yet; it is not a zero-percent result.": "এই পেজে শুধু আপনার অ্যাকাউন্টের তথ্য দেখায়। দলগুলোর তুলনার জন্য পরিচালকের মোট প্রতিবেদন দরকার। ফল পাওয়া যাচ্ছে না মানে এখনো যোগ্য পর্যবেক্ষণ নেই; এটি শূন্য শতাংশ ফল নয়।",
    "Planning completion is your acknowledgement, not a test of financial understanding. Each account has one planning task and one recurring setup task for this study. Retention checks activity on Dhaka calendar days 30–36, 60–66 or 90–96 after enrolment; the full window must finish first. Support reports cover issues recorded here, rather than external support calls.": "পরিকল্পনা সম্পন্ন মানে আপনার পর্যালোচনা নিশ্চিত করা; আর্থিক বোঝাপড়ার পরীক্ষা নয়। প্রতিটি অ্যাকাউন্টের একটি পরিকল্পনা ও একটি নিয়মিত পেমেন্ট তৈরির কাজ আছে। ধরে রাখার হার দেখে যোগ দেওয়ার ৩০–৩৬, ৬০–৬৬ বা ৯০–৯৬তম ঢাকার দিনের ব্যবহার; পুরো সময়সীমা শেষ হতে হবে। সহায়তার প্রতিবেদনে এখানে লেখা সমস্যাই গণনা হয়।",
    "Day 30 activity retention": "৩০তম দিনের ব্যবহারে ধরে রাখার হার",
    "Day 60 activity retention": "৬০তম দিনের ব্যবহারে ধরে রাখার হার",
    "Day 90 activity retention": "৯০তম দিনের ব্যবহারে ধরে রাখার হার",
    "Planning reviews acknowledged": "নিশ্চিত করা পরিকল্পনা পর্যালোচনা",
    "Recurring payment setup": "নিয়মিত পেমেন্ট তৈরি",
    "Due simulated Auto Pay completion": "নির্ধারিত ডেমো অটো পে সম্পন্ন",
    "Initiated simulated transactions, first 30 days": "প্রথম ৩০ দিনে শুরু করা ডেমো লেনদেন",
    "Support reports, first 30 days": "প্রথম ৩০ দিনের সহায়তার প্রতিবেদন",
    "Describe your experience": "আপনার অভিজ্ঞতা জানান",
    "Which problem matters most?": "কোন সমস্যাটি সবচেয়ে গুরুত্বপূর্ণ?",
    "Knowing what I can safely spend": "কত টাকা খরচের পরিকল্পনা করতে পারি তা জানা",
    "Remembering recurring payments": "নিয়মিত পেমেন্ট মনে রাখা",
    "Both": "দুটিই",
    "Usefulness (1 = low, 5 = high)": "উপকারিতা (১ = কম, ৫ = বেশি)",
    "Ease of completing the task (1 = difficult, 5 = easy)": "কাজটি করার সহজতা (১ = কঠিন, ৫ = সহজ)",
    "Payments you missed in the past 30 days (0–30)": "গত ৩০ দিনে বাদ পড়া পেমেন্ট (০–৩০)",
    "What was useful or confusing? (optional)": "কী কাজে লেগেছে বা বুঝতে অসুবিধা হয়েছে? (ঐচ্ছিক)",
    "Record research response": "গবেষণার উত্তর সংরক্ষণ করুন",
    "Record a help issue": "সহায়তার প্রয়োজন জানান",
    "Where did you need help?": "কোন বিষয়ে সাহায্য দরকার হয়েছে?",
    "Financial planning": "আর্থিক পরিকল্পনা",
    "Recurring payment": "নিয়মিত পেমেন্ট",
    "Describe the issue": "সমস্যাটি লিখুন",
    "Record help issue": "সহায়তার সমস্যা সংরক্ষণ করুন",
    "Your recent responses": "আপনার সাম্প্রতিক উত্তর",
    "Help issue": "সহায়তার সমস্যা",
    "Research response": "গবেষণার উত্তর",
    "This is a wallet prototype. Every payment is simulated, including payments made by real research participants. The study does not establish real revenue or financial improvement.": "এটি ওয়ালেটের একটি প্রোটোটাইপ। প্রকৃত গবেষণার অংশগ্রহণকারীর পেমেন্টসহ সব পেমেন্ট ডেমো। এই গবেষণা প্রকৃত আয় বা আর্থিক উন্নতি প্রমাণ করে না।",
    "Research answers are self-reported. They help identify needs but do not prove adoption or financial impact.": "গবেষণার উত্তর আপনার নিজের দেওয়া তথ্য। এটি প্রয়োজন বুঝতে সাহায্য করে, তবে ব্যবহার বৃদ্ধি বা আর্থিক উপকারের প্রমাণ নয়।",
    "This records a support need for the study operator. It does not contact a live support center.": "এটি গবেষণার পরিচালকের জন্য সহায়তার প্রয়োজন সংরক্ষণ করে। কোনো সরাসরি সহায়তা কেন্দ্রে যোগাযোগ করে না।",
    "Learned from transaction patterns": "লেনদেনের ধরন থেকে শেখা",
    "7-day spending forecast": "৭ দিনের খরচের পূর্বাভাস",
    "Experimental": "পরীক্ষামূলক",
    "synthetic training": "কৃত্রিম তথ্য দিয়ে প্রশিক্ষিত",
    "Expected everyday money out": "সম্ভাব্য দৈনন্দিন খরচ",
    "Empirical error range": "পরীক্ষায় পাওয়া ত্রুটির পরিসর",
    "After recorded commitments": "নির্ধারিত পেমেন্ট বাদ দেওয়ার পর",
    "Everyday spending still expected": "আরও সম্ভাব্য দৈনন্দিন খরচ",
    "Illustrative balance after spending": "সম্ভাব্য খরচের পর উদাহরণভিত্তিক ব্যালেন্স",
    "Forecast not available yet": "পূর্বাভাস এখনো পাওয়া যাচ্ছে না",
    "At least 28 complete days of wallet history are needed to estimate everyday spending.": "দৈনন্দিন খরচের পূর্বাভাসের জন্য অন্তত ২৮টি সম্পূর্ণ দিনের ওয়ালেটের ইতিহাস দরকার।",
    "There is not enough everyday spending activity in the last 28 days for a useful forecast.": "কার্যকর পূর্বাভাসের জন্য গত ২৮ দিনে পর্যাপ্ত দৈনন্দিন খরচের তথ্য নেই।",
    "Some wallet history needs review before a forecast can be shown.": "পূর্বাভাস দেখানোর আগে ওয়ালেটের কিছু তথ্য পর্যালোচনা করতে হবে।",
    "The forecast is temporarily unavailable. Please try again later.": "পূর্বাভাস সাময়িকভাবে পাওয়া যাচ্ছে না। পরে আবার চেষ্টা করুন।",
    "Your recorded commitments and balance estimate above remain available.": "উপরের নির্ধারিত পেমেন্ট ও ব্যালেন্সের হিসাব দেখতে পারবেন।",
    "Model and evaluation evidence": "মডেল ও মূল্যায়নের প্রমাণ",
    "Download model evaluation": "মডেলের মূল্যায়ন ডাউনলোড করুন",
    "Model": "মডেল",
    "Held-out mean absolute error": "আলাদা পরীক্ষায় গড় পরম ত্রুটি",
    "28-day mean baseline error": "২৮ দিনের গড়ভিত্তিক তুলনার ত্রুটি",
    "Held-out forecast examples": "আলাদা পরীক্ষার পূর্বাভাসের সংখ্যা",
    "Review payment plan": "পেমেন্টের পরিকল্পনা দেখুন",
    "Review your weekly plan": "সাপ্তাহিক পরিকল্পনা দেখুন",
    "I reviewed my recorded commitments and know what is due this week.": "আমি নির্ধারিত পেমেন্ট দেখেছি এবং এই সপ্তাহে কী পরিশোধ করতে হবে জানি।",
    "Record planning review": "পরিকল্পনা পর্যালোচনা সংরক্ষণ করুন",
    "This records a self-reported task outcome for the pilot. It does not confirm affordability or change any payment.": "এটি পাইলটে আপনার কাজের স্বপ্রতিবেদিত ফল সংরক্ষণ করে। এটি সামর্থ্য নিশ্চিত করে না বা পেমেন্ট পরিবর্তন করে না।",
    "The model uses your previous 28 complete days. Scheduled payments and Pay Later repayments are excluded because your recorded commitments are reserved separately. The range comes from synthetic calibration errors; it does not guarantee accuracy for your wallet.": "মডেলটি আগের ২৮টি সম্পূর্ণ দিনের তথ্য ব্যবহার করে। নির্ধারিত পেমেন্ট ও পে লেটার পরিশোধের টাকা আলাদা হিসাবে রাখা হয়, তাই এগুলো বাদ দেওয়া হয়। পরিসরটি কৃত্রিম তথ্যের পরীক্ষার ত্রুটি থেকে এসেছে; আপনার ওয়ালেটের নির্ভুলতার নিশ্চয়তা নয়।",
    "Already posted everyday spending today is subtracted from the forecast before this calculation. This planning scenario assumes no new wallet inflows. It does not reserve or move money.": "এই হিসাবের আগে আজ ইতিমধ্যে হওয়া দৈনন্দিন খরচ পূর্বাভাস থেকে বাদ দেওয়া হয়। এই উদাহরণে নতুন টাকা আসবে না ধরে নেওয়া হয়েছে। এটি টাকা আটকে রাখে না বা স্থানান্তর করে না।",
    "Recorded commitments and expected spending exceed your current balance. Review your upcoming payments and funding plan.": "নির্ধারিত পেমেন্ট ও সম্ভাব্য খরচ বর্তমান ব্যালেন্সের চেয়ে বেশি। আসন্ন পেমেন্ট ও টাকার পরিকল্পনা দেখুন।",
    "The current evaluation demonstrates the implementation on synthetic histories. Real customer forecasting accuracy and customer impact have not yet been validated.": "বর্তমান মূল্যায়ন কৃত্রিম লেনদেনের ইতিহাসে বাস্তবায়ন দেখায়। প্রকৃত গ্রাহকের পূর্বাভাসের নির্ভুলতা ও উপকার এখনো যাচাই করা হয়নি।",
}
