"""Bangla copy for wallet screens, validation and their local interactions."""

WALLET_BANGLA = {
    "Cash Out": "ক্যাশ আউট", "Send Money": "টাকা পাঠান", "Transfer Money": "টাকা ট্রান্সফার",
    "Add Money": "টাকা যোগ করুন", "Balance": "ব্যালেন্স", "Amount": "পরিমাণ",
    "Agent & ATM": "এজেন্ট ও এটিএম", "Bank & Visa": "ব্যাংক ও ভিসা",
    "Agent Cash Out": "এজেন্ট ক্যাশ আউট", "ATM Cash Out": "এটিএম ক্যাশ আউট",
    "Cash-out channel": "ক্যাশ আউটের মাধ্যম", "Transfer destination": "ট্রান্সফারের গন্তব্য",
    "Choose an agent or ATM and review your fee and remaining balance.": "এজেন্ট বা এটিএম বাছুন এবং ফি ও অবশিষ্ট ব্যালেন্স দেখুন।",
    "Agent Number": "এজেন্টের নম্বর", "Demo ATM Location": "ডেমো এটিএমের অবস্থান",
    "Enter an agent number to check its registered name and safety status.": "নিবন্ধিত নাম ও নিরাপত্তা অবস্থা দেখতে এজেন্টের নম্বর দিন।",
    "Suggested withdrawal amounts": "উত্তোলনের প্রস্তাবিত পরিমাণ",
    "ATM: demo fee 1%; withdraw multiples of ৳500, up to ৳20,000.": "এটিএম: ডেমো ফি ১%; ৫০০ টাকার গুণিতকে সর্বোচ্চ ২০,০০০ টাকা উত্তোলন করুন।",
    "Agent: demo fee 1.5%; the fee is included in your total wallet deduction.": "এজেন্ট: ডেমো ফি ১.৫%; মোট ওয়ালেট কর্তনের মধ্যে এই ফি রয়েছে।",
    "Confirm Demo Cash Out": "ডেমো ক্যাশ আউট নিশ্চিত করুন",
    "These locations and fees are examples for this demo. A successful cash-out updates your demo wallet and creates a receipt; it does not dispense physical cash.": "এখানকার অবস্থান ও ফি ডেমোর উদাহরণ। সফল ক্যাশ আউটে আপনার ডেমো ওয়ালেট পরিবর্তন হয় এবং রসিদ তৈরি হয়; বাস্তবে নগদ টাকা দেওয়া হয় না।",
    "Check the destination and total deduction before confirming. Your receipt shows the amount, fee, transaction ID and reference.": "নিশ্চিত করার আগে গন্তব্য ও মোট কর্তন যাচাই করুন। রসিদে পরিমাণ, ফি, লেনদেন আইডি ও রেফারেন্স থাকবে।",
    "Withdrawal / transfer amount": "উত্তোলন / ট্রান্সফারের পরিমাণ", "Service fee": "সেবা ফি",
    "Total deduction": "মোট কর্তন", "Remaining balance": "অবশিষ্ট ব্যালেন্স",
    "Wallet deduction preview": "ওয়ালেট কর্তনের পূর্বাভাস",
    "Enter an amount to see your exact fee and remaining balance.": "সঠিক ফি ও অবশিষ্ট ব্যালেন্স দেখতে পরিমাণ লিখুন।",
    "Calculating fee and remaining balance...": "ফি ও অবশিষ্ট ব্যালেন্স হিসাব করা হচ্ছে...",
    "Review your destination and total before confirming.": "নিশ্চিত করার আগে গন্তব্য ও মোট পরিমাণ যাচাই করুন।",
    "Insufficient balance including the service fee.": "সেবা ফিসহ পরিশোধের জন্য পর্যাপ্ত ব্যালেন্স নেই।",
    "Fee preview timed out. Enter the amount again to retry.": "ফির হিসাব পেতে সময় শেষ হয়েছে। আবার চেষ্টা করতে পরিমাণ লিখুন।",
    "Unable to calculate this amount.": "এই পরিমাণের হিসাব করা যায়নি।",
    "Unable to calculate this amount. Please refresh.": "এই পরিমাণের হিসাব করা যায়নি। পেজটি রিফ্রেশ করুন।",
    "Record a demo transfer to a bank account or Visa card.": "ব্যাংক অ্যাকাউন্ট বা ভিসা কার্ডে ডেমো ট্রান্সফার নথিভুক্ত করুন।",
    "Bank Account": "ব্যাংক অ্যাকাউন্ট", "Visa Card": "ভিসা কার্ড", "Demo Bank": "ডেমো ব্যাংক",
    "Choose a demo bank": "একটি ডেমো ব্যাংক বাছুন", "Transfer Method": "ট্রান্সফারের পদ্ধতি",
    "demo fee": "ডেমো ফি", "Account Number": "অ্যাকাউন্ট নম্বর",
    "Demo Visa Card Number": "ডেমো ভিসা কার্ড নম্বর", "Account Holder Name": "অ্যাকাউন্টধারীর নাম",
    "Card Holder Name": "কার্ডধারীর নাম", "Demo recipient name": "ডেমো প্রাপকের নাম",
    "Note (optional)": "নোট (ঐচ্ছিক)", "Confirm Demo Transfer": "ডেমো ট্রান্সফার নিশ্চিত করুন",
    "Use the sample card number above. Demo Visa fee: 1%. Card numbers are masked in stored records.": "উপরের নমুনা কার্ড নম্বর ব্যবহার করুন। ডেমো ভিসা ফি: ১%। সংরক্ষিত রেকর্ডে কার্ড নম্বরের শুধু শেষ চার সংখ্যা দেখানো হয়।",
    "This demo records an outgoing transfer and deducts your demo wallet balance, including the displayed fee. No money reaches a real bank account or card. The receipt success status confirms the local demo record.": "এই ডেমোতে দেখানো ফিসহ আপনার ডেমো ওয়ালেট থেকে টাকা কেটে ট্রান্সফার নথিভুক্ত করা হয়। বাস্তব ব্যাংক অ্যাকাউন্ট বা কার্ডে টাকা যায় না। রসিদের সফল অবস্থা শুধু এই স্থানীয় ডেমো রেকর্ড নিশ্চিত করে।",
    "Bank destinations are offline examples. NPSB and BEFTN are selectable demonstration methods; their fees and timing here do not represent live bank terms.": "ব্যাংকের গন্তব্যগুলো অফলাইন উদাহরণ। ডেমো পদ্ধতি হিসেবে NPSB ও BEFTN বাছা যায়; এখানকার ফি ও সময় বাস্তব ব্যাংকের শর্ত নয়।",
    "Send Money to a Wallet": "ওয়ালেটে টাকা পাঠান", "UpayX to Visa": "UpayX থেকে ভিসায়",
    "Transfer": "ট্রান্সফার", "Recipient Mobile": "প্রাপকের মোবাইল নম্বর",
    "Transfer demo wallet balance to another registered wallet account.": "অন্য নিবন্ধিত ওয়ালেট অ্যাকাউন্টে ডেমো ব্যালেন্স পাঠান।",
    "Enter a number to check its registered name and safety status.": "নিবন্ধিত নাম ও নিরাপত্তা অবস্থা দেখতে নম্বর লিখুন।",
    "Lunch, rent, payment...": "খাবার, ভাড়া, পেমেন্ট...", "Demo Wallet Transfer": "ডেমো ওয়ালেট ট্রান্সফার",
    "Use the mobile number of an account created in this app. A successful transfer updates both wallets and records the same reference in both accounts. All funds are demo funds.": "এই অ্যাপে তৈরি অ্যাকাউন্টের মোবাইল নম্বর ব্যবহার করুন। সফল ট্রান্সফারে উভয় ওয়ালেটের ব্যালেন্স বদলে যায় এবং দুই অ্যাকাউন্টে একই রেফারেন্স থাকে। সব অর্থই ডেমো অর্থ।",
    "Wallet": "ওয়ালেট", "Source": "উৎস", "Debit / Credit Card": "ডেবিট / ক্রেডিট কার্ড", "Agent": "এজেন্ট",
    "Add demo balance from a mock source.": "নমুনা উৎস থেকে ডেমো ব্যালেন্স যোগ করুন।",
    "This adds local demo funds and records the selected source in your transaction history.": "এটি স্থানীয় ডেমো অর্থ যোগ করে এবং নির্বাচিত উৎস আপনার লেনদেনের ইতিহাসে রাখে।",
    "Transaction summary": "লেনদেনের সারাংশ", "Transaction receipt": "লেনদেনের রসিদ", "Transaction details": "লেনদেনের বিবরণ",
    "Open Report": "রিপোর্ট খুলুন", "Account holder": "অ্যাকাউন্টধারী", "Wallet number": "ওয়ালেট নম্বর",
    "Reference": "রেফারেন্স", "Transaction ID": "লেনদেন আইডি", "Date and time (BD)": "তারিখ ও সময় (বাংলাদেশ)",
    "Type": "ধরন", "Counterparty / provider": "প্রাপক / সেবাদাতা", "Direction": "প্রবাহের দিক",
    "Money in": "টাকা এসেছে", "Money out": "টাকা গেছে", "Fee": "ফি", "Wallet change": "ওয়ালেটের পরিবর্তন",
    "Note": "নোট", "No note": "কোনো নোট নেই", "Invoice number": "ইনভয়েস নম্বর",
    "Bill account": "বিলের অ্যাকাউন্ট", "Bill invoice reference": "বিল ইনভয়েসের রেফারেন্স",
    "Print / download receipt": "রসিদ প্রিন্ট / ডাউনলোড করুন", "Choose format": "ফরম্যাট বাছুন",
    "Image (.jpg)": "ছবি (.jpg)", "Download receipt": "রসিদ ডাউনলোড করুন",
    "The download includes the full record, fees, a transaction summary and documentation. Open the downloaded file to print it.": "ডাউনলোডে সম্পূর্ণ রেকর্ড, ফি, লেনদেনের সারাংশ ও ব্যাখ্যা থাকবে। প্রিন্ট করতে ডাউনলোড করা ফাইলটি খুলুন।",
    "Record documentation": "রেকর্ডের ব্যাখ্যা",
    "Amount is the payment or transfer principal. Fee is the service charge. Wallet change shows the actual credit or deduction, including fees for money out. Only successful transactions change the completed totals in Report.": "পরিমাণ হলো পেমেন্ট বা ট্রান্সফারের মূল অর্থ। ফি হলো সেবা খরচ। ওয়ালেটের পরিবর্তনে প্রকৃত জমা বা কর্তন দেখানো হয়; টাকা বের হলে ফিও ধরা হয়। শুধু সফল লেনদেন রিপোর্টের সম্পন্ন মোট পরিমাণ বদলায়।",
    "All amounts use BDT. Dates and times use Bangladesh time (UTC+6). This receipt documents the hackathon demo wallet.": "সব পরিমাণ বাংলাদেশি টাকায়। তারিখ ও সময় বাংলাদেশ সময়ে (UTC+6)। এই রসিদ হ্যাকাথনের ডেমো ওয়ালেটের রেকর্ড।",
    "Payment instruction": "পেমেন্ট নির্দেশনা", "Scheduled payment summary": "নির্ধারিত পেমেন্টের সারাংশ",
    "Schedule details": "সময়সূচির বিবরণ", "Schedule ID": "সময়সূচি আইডি",
    "Due date and time (BD)": "নির্ধারিত তারিখ ও সময় (বাংলাদেশ)", "Recipient / authorization": "প্রাপক / অনুমোদন",
    "Recipient / account number": "প্রাপক / অ্যাকাউন্ট নম্বর", "Provider": "সেবাদাতা", "Category": "বিভাগ",
    "Mode": "পদ্ধতি", "Auto pay": "স্বয়ংক্রিয় পেমেন্ট", "Manual payment": "নিজে পেমেন্ট করুন",
    "Frequency": "পুনরাবৃত্তি", "One Time": "একবার", "Monthly": "মাসিক", "Processing message": "প্রক্রিয়াকরণের বার্তা",
    "View completed transaction receipt": "সম্পন্ন লেনদেনের রসিদ দেখুন", "Print / download schedule": "সময়সূচি প্রিন্ট / ডাউনলোড করুন",
    "Download summary": "সারাংশ ডাউনলোড করুন",
    "Scheduled amounts are reported separately from wallet transactions. A completed schedule links to its ledger receipt and is never counted twice.": "নির্ধারিত পরিমাণ ওয়ালেটের লেনদেন থেকে আলাদাভাবে দেখানো হয়। সম্পন্ন সময়সূচিতে মূল লেনদেনের রসিদ যুক্ত থাকে; একই অর্থ দুইবার গোনা হয় না।",
    "Success": "সফল", "Pending": "অপেক্ষমাণ", "Failed": "ব্যর্থ", "Cancelled": "বাতিল", "Completed": "সম্পন্ন", "Scheduled": "নির্ধারিত",
    "Cash Out (Agent)": "ক্যাশ আউট (এজেন্ট)", "Cash Out (ATM)": "ক্যাশ আউট (এটিএম)",
    "Bank Transfer (NPSB)": "ব্যাংক ট্রান্সফার (NPSB)", "Bank Transfer (BEFTN)": "ব্যাংক ট্রান্সফার (BEFTN)",
    "Visa Card Transfer": "ভিসা কার্ডে ট্রান্সফার", "Received Money": "টাকা এসেছে",
    "Amount must be greater than zero.": "পরিমাণ শূন্যের চেয়ে বেশি হতে হবে।",
    "Demo transaction limit is ৳100,000.": "ডেমো লেনদেনের সর্বোচ্চ সীমা ১,০০,০০০ টাকা।",
    "Amount can have at most two decimal places.": "পরিমাণে দশমিকের পরে সর্বোচ্চ দুই ঘর থাকতে পারে।",
    "Enter a valid amount.": "সঠিক পরিমাণ লিখুন।", "User account not found.": "ব্যবহারকারীর অ্যাকাউন্ট পাওয়া যায়নি।",
    "You cannot send money to your own number.": "নিজের নম্বরে টাকা পাঠানো যায় না।", "Insufficient balance.": "পর্যাপ্ত ব্যালেন্স নেই।",
    "No wallet account found for this number. Create a demo account first.": "এই নম্বরের ওয়ালেট অ্যাকাউন্ট নেই। আগে একটি ডেমো অ্যাকাউন্ট তৈরি করুন।",
    "Note must be 255 characters or fewer.": "নোট সর্বোচ্চ ২৫৫ অক্ষরের হতে পারে।",
    "Choose a valid add-money source.": "টাকা যোগ করার সঠিক উৎস বাছুন।",
    "Choose Agent or ATM cash-out.": "এজেন্ট বা এটিএম ক্যাশ আউট বাছুন।",
    "Choose NPSB or BEFTN (BFTN).": "NPSB বা BEFTN (BFTN) বাছুন।",
    "Demo ATM withdrawals must be multiples of ৳500, up to ৳20,000.": "ডেমো এটিএমে ৫০০ টাকার গুণিতকে সর্বোচ্চ ২০,০০০ টাকা উত্তোলন করা যায়।",
    "Choose Bank Account or Visa Card.": "ব্যাংক অ্যাকাউন্ট বা ভিসা কার্ড বাছুন।",
    "Choose a supported wallet operation.": "সমর্থিত ওয়ালেট সেবা বাছুন।",
    "Choose a listed demo ATM location.": "তালিকা থেকে ডেমো এটিএমের অবস্থান বাছুন।",
    "Insufficient balance including cash-out fee.": "ক্যাশ আউট ফিসহ পর্যাপ্ত ব্যালেন্স নেই।",
    "Enter a 16-digit demo Visa card number beginning with 4.": "৪ দিয়ে শুরু হওয়া ১৬ সংখ্যার ডেমো ভিসা কার্ড নম্বর লিখুন।",
    "The demo Visa card number did not pass its checksum.": "ডেমো ভিসা কার্ড নম্বরের গাণিতিক যাচাই মেলেনি।",
    "Enter the destination account or card holder name (2–120 characters).": "প্রাপক অ্যাকাউন্ট বা কার্ডধারীর নাম লিখুন (২–১২০ অক্ষর)।",
    "Transfer note must be 100 characters or fewer.": "ট্রান্সফারের নোট সর্বোচ্চ ১০০ অক্ষরের হতে পারে।",
    "Choose a listed demo bank.": "তালিকা থেকে একটি ডেমো ব্যাংক বাছুন।",
    "Enter a demo bank account number with 6–20 digits.": "৬–২০ সংখ্যার ডেমো ব্যাংক অ্যাকাউন্ট নম্বর লিখুন।",
    "Insufficient balance including transfer fee.": "ট্রান্সফার ফিসহ পর্যাপ্ত ব্যালেন্স নেই।",
    "Payment note must be 255 characters or fewer.": "পেমেন্টের নোট সর্বোচ্চ ২৫৫ অক্ষরের হতে পারে।",
    "Money sent successfully.": "সফলভাবে টাকা পাঠানো হয়েছে।", "Money added successfully.": "সফলভাবে টাকা যোগ হয়েছে।",
    "Cash-out completed successfully.": "ক্যাশ আউট সফলভাবে সম্পন্ন হয়েছে।",
    "Demo transfer recorded. No funds were sent to an external bank or card.": "ডেমো ট্রান্সফার নথিভুক্ত হয়েছে। বাইরের ব্যাংক বা কার্ডে কোনো অর্থ পাঠানো হয়নি।",
    "The start date must be on or before the end date.": "শুরুর তারিখ শেষ তারিখের আগে বা একই দিনে হতে হবে।",
    "Choose PDF or Excel (.xlsx).": "PDF বা Excel (.xlsx) বাছুন।", "Choose PDF or JPG.": "PDF বা JPG বাছুন।",
    "This form was already submitted. Open a new form to change the details.": "এই ফর্ম ইতিমধ্যে জমা হয়েছে। তথ্য বদলাতে নতুন ফর্ম খুলুন।",
    "This transaction was already completed. Showing the original receipt.": "এই লেনদেন ইতিমধ্যে সম্পন্ন হয়েছে। আগের রসিদ দেখানো হচ্ছে।",
    "Refresh this form before submitting again.": "আবার জমা দেওয়ার আগে ফর্মটি রিফ্রেশ করুন।",
}

_BANK_CITIES = ("ঢাকা", "চট্টগ্রাম", "সিলেট", "রাজশাহী", "খুলনা", "বরিশাল", "রংপুর", "ময়মনসিংহ", "কুমিল্লা", "গাজীপুর", "নারায়ণগঞ্জ", "বগুড়া")
_ATM_PLACES = ("গুলশান, ঢাকা", "বনানী, ঢাকা", "ধানমন্ডি, ঢাকা", "মতিঝিল, ঢাকা", "মিরপুর, ঢাকা", "আগ্রাবাদ, চট্টগ্রাম", "জিন্দাবাজার, সিলেট", "সাহেব বাজার, রাজশাহী", "সোনাডাঙ্গা, খুলনা", "সদর রোড, বরিশাল", "জাহাজ কোম্পানি, রংপুর", "গাঙ্গিনারপাড়, ময়মনসিংহ")

from app.services.wallet_catalog import DEMO_ATMS, DEMO_BANKS

WALLET_BANGLA.update({name: f"ডেমো ব্যাংক {index:02d} — {city}" for index, (name, city) in enumerate(zip(DEMO_BANKS, _BANK_CITIES), 1)})
WALLET_BANGLA.update({name: f"ডেমো এটিএম — {place}" for name, place in zip(DEMO_ATMS.values(), _ATM_PLACES)})
