"""Manually authored Bangla for payments, sign-in and payment planning."""


EXTRA_BANGLA = {
    # Sign-in and account creation.
    "AI Hackathon Demo": "এআই হ্যাকাথন ডেমো",
    "Secure sign in": "নিরাপদ প্রবেশ",
    "Scheduled payment": "পরিকল্পিত পেমেন্ট",
    "Manage Auto Pay": "অটো পে পরিচালনা করুন",
    "Plan your week, manage recurring payments and review your wallet activity.": "সপ্তাহের পরিকল্পনা করুন, নিয়মিত পেমেন্ট পরিচালনা করুন এবং ওয়ালেটের কার্যক্রম দেখুন।",
    "Create an account and verify your mobile number. New accounts start with zero balance.": "অ্যাকাউন্ট তৈরি করে মোবাইল নম্বর যাচাই করুন। নতুন অ্যাকাউন্টের প্রাথমিক ব্যালেন্স শূন্য।",
    "Payments are due at midnight Bangladesh time. Auto Pay runs in the scheduler or when you select Process Due Auto Pay. Opening a page does not execute payments. A failed payment does not deduct balance and is recorded with its reason.": "বাংলাদেশ সময় রাত ১২টায় পেমেন্টের সময় হয়। সময়সূচি কর্মী চালু থাকলে বা ‘নির্ধারিত অটো পে চালান’ নির্বাচন করলে অটো পে চলে। পৃষ্ঠা খুললে পেমেন্ট হয় না। পেমেন্ট ব্যর্থ হলে ব্যালেন্স কাটে না এবং ব্যর্থতার কারণ রাখা হয়।",
    "Welcome to": "স্বাগতম",
    "Sign in with your mobile number to open your wallet dashboard.": "আপনার ওয়ালেট খুলতে মোবাইল নম্বর দিয়ে প্রবেশ করুন।",
    "or": "অথবা",
    "Create account": "অ্যাকাউন্ট তৈরি করুন",
    "Demo user": "ডেমো ব্যবহারকারী",
    "Demo user:": "ডেমো ব্যবহারকারী:",
    "Demo OTP:": "ডেমো ওটিপি:",
    "Full Name": "পুরো নাম",
    "Responsive Fintech Experience": "কম্পিউটার ও মোবাইলে আর্থিক সেবা",
    "One web app.": "একটি ওয়েব অ্যাপ।",
    "Desktop + mobile.": "কম্পিউটার ও মোবাইলে ব্যবহার করুন।",
    "Wallet, transfers, payments, recharge, history and profile — organized using a clean Flask architecture.": "এক জায়গায় ওয়ালেট, টাকা পাঠানো, পেমেন্ট, রিচার্জ, লেনদেনের ইতিহাস ও প্রোফাইল ব্যবহার করুন।",
    "Create wallet": "ওয়ালেট তৈরি করুন",
    "Sign up": "নিবন্ধন করুন",
    "This is a hackathon prototype. New accounts receive demo balance only.": "এটি হ্যাকাথনের নমুনা অ্যাপ। নতুন অ্যাকাউন্টে শুধু ডেমো ব্যালেন্স দেওয়া হয়।",
    "Your full name": "আপনার পুরো নাম",
    "Email (optional)": "ইমেইল (ঐচ্ছিক)",
    "Already have an account? Sign in": "অ্যাকাউন্ট আছে? প্রবেশ করুন",
    "Secure verification": "নিরাপদ যাচাই",
    "OTP Verification": "ওটিপি যাচাই",
    "Verify your mobile": "মোবাইল নম্বর যাচাই করুন",
    "Enter the 6-digit demo OTP for": "এই নম্বরের জন্য ৬ সংখ্যার ডেমো ওটিপি লিখুন",
    "Verify & Continue": "যাচাই করে এগিয়ে যান",
    "No account found. Please create an account first.": "অ্যাকাউন্ট পাওয়া যায়নি। আগে একটি অ্যাকাউন্ট তৈরি করুন।",
    "An account with this mobile number already exists.": "এই মোবাইল নম্বর দিয়ে আগে থেকেই একটি অ্যাকাউন্ট আছে।",
    "Invalid OTP. For the demo, use the OTP shown on this page.": "ওটিপি সঠিক নয়। ডেমোর জন্য এই পাতায় দেখানো ওটিপি লিখুন।",
    "Enter a valid 11-digit Bangladeshi mobile number.": "বাংলাদেশের সঠিক ১১ সংখ্যার মোবাইল নম্বর লিখুন।",
    "Full name must contain 3 to 120 characters.": "পুরো নামে ৩ থেকে ১২০টি অক্ষর থাকতে হবে।",
    "Enter a valid email address.": "সঠিক ইমেইল ঠিকানা লিখুন।",
    "Account created. Verify the demo OTP to continue.": "অ্যাকাউন্ট তৈরি হয়েছে। এগোতে ডেমো ওটিপি যাচাই করুন।",
    "Account not found. Please sign in again.": "অ্যাকাউন্ট পাওয়া যায়নি। আবার প্রবেশ করুন।",
    "Signed out successfully.": "সফলভাবে বের হয়েছেন।",
    # Categories, bill inputs and recharge.
    "Government Payment": "সরকারি পেমেন্ট",
    "Toll Payment": "টোল পেমেন্ট",
    "Choose the category, its provider and your payment reference.": "সেবার ধরন, সেবাদাতা ও বিলের রেফারেন্স বেছে নিন।",
    "Bill / Service Category": "বিল / সেবার ধরন",
    "Choose a category": "সেবার ধরন বেছে নিন",
    "Update category": "সেবার ধরন বদলান",
    "Account / Payment Reference": "অ্যাকাউন্ট / পেমেন্ট রেফারেন্স",
    "Customer / Meter Number": "গ্রাহক / মিটার নম্বর",
    "Customer / Account Number": "গ্রাহক / অ্যাকাউন্ট নম্বর",
    "Subscriber / Customer ID": "সংযোগ / গ্রাহক নম্বর",
    "Customer / Bill Number": "গ্রাহক / বিল নম্বর",
    "Subscriber / Smart Card Number": "গ্রাহক / স্মার্ট কার্ড নম্বর",
    "Statement / Payment Reference": "বিলের বিবরণী / পেমেন্ট রেফারেন্স",
    "Student / Invoice Number": "শিক্ষার্থী / চালান নম্বর",
    "Fine / Case Reference": "জরিমানা / মামলার রেফারেন্স",
    "Vehicle / Toll Reference": "গাড়ি / টোল রেফারেন্স",
    "Application / Challan Number": "আবেদন / চালান নম্বর",
    "Policy / Premium Reference": "বিমা পলিসি / প্রিমিয়াম রেফারেন্স",
    "Donation / Campaign Reference": "অনুদান / কর্মসূচির রেফারেন্স",
    "Booking / Ticket Reference": "বুকিং / টিকিট রেফারেন্স",
    "Booking / Invoice Reference": "বুকিং / চালানের রেফারেন্স",
    "Enter the reference from your bill": "আপনার বিলের রেফারেন্স লিখুন",
    "Enter your reference to check the registered account or authorizing provider.": "নিবন্ধিত অ্যাকাউন্ট বা সেবাদাতা যাচাই করতে বিলের রেফারেন্স লিখুন।",
    "Bill Invoice Reference (Optional)": "বিলের চালান নম্বর (ঐচ্ছিক)",
    "Enter the invoice number printed on the bill": "বিলে লেখা চালান নম্বর লিখুন",
    "A unique invoice number and transaction reference are generated for every completed payment. A supplied provider invoice cannot be paid twice. Demo payment reduces wallet balance; no payment is sent to the provider.": "প্রতিটি সফল পেমেন্টের জন্য আলাদা চালান নম্বর ও লেনদেনের রেফারেন্স তৈরি হয়। একই সেবাদাতার চালান নম্বর দেওয়া হলে সেই চালান দ্বিতীয়বার পরিশোধ করা যায় না। ডেমো পেমেন্টে ওয়ালেটের ব্যালেন্স কমে; সেবাদাতার কাছে বাস্তব টাকা পাঠানো হয় না।",
    "Pay with Demo Balance": "ডেমো ব্যালেন্স দিয়ে পরিশোধ করুন",
    "Choose an operator and recharge using demo balance.": "অপারেটর বেছে নিয়ে ডেমো ব্যালেন্স দিয়ে রিচার্জ করুন।",
    "Choose an operator": "অপারেটর বেছে নিন",
    "Enter a number to check its registered name and safety status.": "নিবন্ধিত নাম ও নিরাপত্তার অবস্থা যাচাই করতে নম্বর লিখুন।",
    "Demo recharge reduces wallet balance and appears in Report. No airtime is delivered.": "ডেমো রিচার্জে ওয়ালেটের ব্যালেন্স কমে এবং রিপোর্টে তথ্য থাকে। মোবাইলে বাস্তব রিচার্জ দেওয়া হয় না।",
    "Recharge with Demo Balance": "ডেমো ব্যালেন্স দিয়ে রিচার্জ করুন",
    "Demo mobile recharge completed and recorded in Report.": "ডেমো রিচার্জ সম্পন্ন হয়েছে এবং রিপোর্টে তথ্য রাখা হয়েছে।",
    "Payment services use demo wallet balance. Provider examples have no live integrations.": "পেমেন্টে ডেমো ওয়ালেটের ব্যালেন্স ব্যবহৃত হয়। নমুনা সেবাদাতাদের সঙ্গে বাস্তব সংযোগ নেই।",
    "Provider examples have no live integrations.": "নমুনা সেবাদাতাদের সঙ্গে বাস্তব সংযোগ নেই।",
    "Choose a supported mobile operator.": "তালিকা থেকে মোবাইল অপারেটর বেছে নিন।",
    "Choose a valid bill category.": "তালিকা থেকে সঠিক বিলের ধরন বেছে নিন।",
    "Enter a valid account or payment reference (2–60 letters, numbers, spaces or / . _ -).": "সঠিক অ্যাকাউন্ট বা পেমেন্ট রেফারেন্স লিখুন। ২–৬০টি ইংরেজি অক্ষর, সংখ্যা, ফাঁকা স্থান বা / . _ - ব্যবহার করা যাবে।",
    "Enter a valid invoice reference (2–60 letters, numbers, spaces or / . _ -).": "সঠিক চালানের রেফারেন্স লিখুন। ২–৬০টি ইংরেজি অক্ষর, সংখ্যা, ফাঁকা স্থান বা / . _ - ব্যবহার করা যাবে।",
    "This provider invoice is already paid. Open its receipt in Report.": "এই সেবাদাতার চালান আগেই পরিশোধ করা হয়েছে। রিপোর্ট থেকে রসিদ দেখুন।",
    "This payment form has expired. Open the payment page again.": "পেমেন্ট ফর্মটি আর ব্যবহার করা যাচ্ছে না। পেমেন্টের পাতা আবার খুলুন।",
    "Amount must be greater than zero.": "টাকার পরিমাণ শূন্যের বেশি হতে হবে।",
    "Demo transaction limit is ৳100,000.": "একটি ডেমো লেনদেনে সর্বোচ্চ ১,০০,০০০ টাকা ব্যবহার করা যাবে।",
    "Amount can have at most two decimal places.": "টাকার পরিমাণে দশমিকের পরে সর্বোচ্চ দুই ঘর লেখা যাবে।",
    "Enter a valid amount.": "টাকার সঠিক পরিমাণ লিখুন।",
    "Insufficient balance.": "ওয়ালেটে পর্যাপ্ত ব্যালেন্স নেই।",
    "User account not found.": "ব্যবহারকারীর অ্যাকাউন্ট পাওয়া যায়নি।",
    # Savings. The rate and beginning-of-month assumption stay explicit.
    "Choose a fixed monthly contribution and tenure. Estimate your maturity amount at a demo annual return of 10%.": "প্রতি মাসে জমার নির্দিষ্ট পরিমাণ ও মেয়াদ বেছে নিন। ডেমো হিসেবে বছরে ১০% লাভ ধরে মেয়াদ শেষে সম্ভাব্য মোট টাকা হিসাব করুন।",
    "Plan Name": "পরিকল্পনার নাম",
    "Emergency fund": "জরুরি খরচের সঞ্চয়",
    "Monthly Contribution (BDT)": "প্রতি মাসে জমার পরিমাণ (টাকা)",
    "Tenure (Months)": "মেয়াদ (মাস)",
    "Tenure: 1–120 months. Annual demo rate: 10%. Each saved plan keeps its monthly contribution and tenure fixed.": "মেয়াদ ১–১২০ মাস। ডেমো বার্ষিক লাভের হার ১০%। সংরক্ষণ করার পরে ওই পরিকল্পনার মাসিক জমার পরিমাণ ও মেয়াদ অপরিবর্তিত থাকবে।",
    "Calculate Savings": "সঞ্চয়ের হিসাব দেখুন",
    "Save Savings Plan": "সঞ্চয় পরিকল্পনা সংরক্ষণ করুন",
    "Your Savings Plan": "আপনার সঞ্চয় পরিকল্পনা",
    "Total contributions": "মোট জমা",
    "Estimated return at 10% annually": "বছরে ১০% হারে সম্ভাব্য লাভ",
    "Estimated maturity": "মেয়াদ শেষে সম্ভাব্য মোট টাকা",
    "Estimate assumes contributions at the start of each month. Simple annual return is prorated for the time each contribution remains saved; it is not compounded. Taxes and fees are excluded. This demo estimate is not a guaranteed return. Saving a plan records your goal and does not open an account or move wallet balance.": "হিসাবে ধরে নেওয়া হয়েছে প্রতি মাসের শুরুতে টাকা জমা হবে। প্রতিটি জমা যত মাস থাকবে, শুধু সেই সময়ের জন্য বছরে ১০% সরল হারে সম্ভাব্য লাভ যোগ করা হয়েছে; লাভের ওপর আবার লাভ ধরা হয়নি। কর ও ফি ধরা হয়নি। এটি ডেমো হিসাব, নিশ্চিত লাভের প্রতিশ্রুতি নয়। পরিকল্পনা সংরক্ষণ করলে শুধু আপনার লক্ষ্য রাখা হয়; সঞ্চয় অ্যাকাউন্ট খোলে না এবং ওয়ালেটের টাকা সরানো হয় না।",
    "Saved Savings Plans": "সংরক্ষিত সঞ্চয় পরিকল্পনা",
    "Plan": "পরিকল্পনা",
    "Monthly": "মাসিক",
    "Contributions": "জমা",
    "Estimated Return": "সম্ভাব্য লাভ",
    "Estimated Maturity": "মেয়াদ শেষে সম্ভাব্য মোট টাকা",
    "Matures": "মেয়াদ শেষ",
    "Action": "করণীয়",
    "Archive": "তালিকা থেকে সরান",
    "Save a plan to keep your fixed contribution, tenure and estimated maturity here.": "মাসিক জমার নির্দিষ্ট পরিমাণ, মেয়াদ ও সম্ভাব্য মোট টাকা এখানে রাখতে একটি পরিকল্পনা সংরক্ষণ করুন।",
    "Choose a savings duration from 1 to 120 months.": "সঞ্চয়ের মেয়াদ ১ থেকে ১২০ মাসের মধ্যে বেছে নিন।",
    "Plan name must be 1 to 80 characters.": "পরিকল্পনার নামে ১ থেকে ৮০টি অক্ষর থাকতে হবে।",
    "You can save up to 10 active savings plans. Archive a plan to add another.": "সর্বোচ্চ ১০টি সক্রিয় সঞ্চয় পরিকল্পনা রাখা যায়। নতুনটি যোগ করতে আগের একটি তালিকা থেকে সরান।",
    "Saved savings plan not found.": "সংরক্ষিত সঞ্চয় পরিকল্পনা পাওয়া যায়নি।",
    "Savings plan archived.": "সঞ্চয় পরিকল্পনাটি তালিকা থেকে সরানো হয়েছে।",
    "Savings plan saved with a fixed monthly amount and tenure.": "নির্দিষ্ট মাসিক জমা ও মেয়াদসহ সঞ্চয় পরিকল্পনা সংরক্ষণ করা হয়েছে।",
    "Fixed monthly contribution": "প্রতি মাসে নির্দিষ্ট জমা",
    "months": "মাস",
    # Money requests.
    "Prepare a message asking someone to send money to your demo wallet.": "আপনার ডেমো ওয়ালেটে টাকা চাওয়ার জন্য একটি বার্তা তৈরি করুন।",
    "Recipient Mobile Number": "প্রাপকের মোবাইল নম্বর",
    "Requested Amount (BDT)": "চাওয়া টাকার পরিমাণ",
    "Note (Optional)": "নোট (ঐচ্ছিক)",
    "What is this request for?": "কী জন্য টাকা চাইছেন?",
    "Prepare Request Message": "টাকা চাওয়ার বার্তা তৈরি করুন",
    "Prepared Request": "টাকা চাওয়ার তৈরি বার্তা",
    "Message to Copy": "কপি করার বার্তা",
    "Prepared money request": "টাকা চাওয়ার তৈরি বার্তা",
    "Copy and share this message yourself. The recipient needs a registered demo wallet to send money. No request is sent automatically and no balance changes until a transfer is completed.": "বার্তাটি নিজে কপি করে পাঠান। টাকা পাঠাতে প্রাপকের নিবন্ধিত ডেমো ওয়ালেট লাগবে। অ্যাপ নিজে অনুরোধ পাঠায় না। টাকা পাঠানো সম্পন্ন না হওয়া পর্যন্ত কোনো ব্যালেন্স বদলায় না।",
    "Clear Prepared Request": "তৈরি বার্তাটি মুছুন",
    "Choose another mobile number to request money from.": "টাকা চাওয়ার জন্য নিজের নম্বর ছাড়া অন্য মোবাইল নম্বর দিন।",
    "Keep the request note within 160 characters.": "টাকা চাওয়ার নোট ১৬০ অক্ষরের মধ্যে রাখুন।",
    "Request message prepared. Share it with the recipient to ask for a demo transfer.": "টাকা চাওয়ার বার্তা তৈরি হয়েছে। ডেমো টাকা পাঠাতে বলার জন্য প্রাপককে বার্তাটি দিন।",
    # Pay Later.
    "Record a deferred demo purchase, choose a due date and repay from your wallet.": "পরে পরিশোধ করবেন এমন ডেমো কেনাকাটা লিখে রাখুন, মেয়াদ বেছে নিন এবং ওয়ালেট থেকে পরিশোধ করুন।",
    "Demo Limit": "ডেমো সীমা",
    "Available": "আরও ব্যবহার করা যাবে",
    "Outstanding": "বাকি টাকা",
    "Overdue": "মেয়াদ পেরিয়ে গেছে",
    "New Deferred Purchase": "পরে পরিশোধের নতুন কেনাকাটা",
    "Demo Merchant": "ডেমো দোকান",
    "Choose a merchant": "দোকান বেছে নিন",
    "Merchant Invoice Reference": "দোকানের চালান নম্বর",
    "Repayment Tenure": "পরিশোধের মেয়াদ",
    "14 days": "১৪ দিন",
    "Local demo only. No lender approval or merchant payment occurs. Your balance stays unchanged until repayment. Demo interest and fees are 0%; no automatic repayment or late fee is charged. Your total outstanding purchases cannot exceed BDT 5,000.": "এটি শুধু স্থানীয় ডেমো। কোনো ঋণদাতার অনুমোদন নেওয়া হয় না বা দোকানকে বাস্তব টাকা দেওয়া হয় না। পরিশোধ করার আগে ব্যালেন্স অপরিবর্তিত থাকে। ডেমো সুদ ও ফি ০%; স্বয়ংক্রিয় পরিশোধ বা বিলম্বের জরিমানা নেই। সব কেনাকাটার মোট বাকি টাকা ৫,০০০ টাকার বেশি হতে পারবে না।",
    "Record Demo Purchase": "ডেমো কেনাকাটা সংরক্ষণ করুন",
    "Purchases and Repayments": "কেনাকাটা ও পরিশোধ",
    "Merchant / Invoice": "দোকান / চালান",
    "Due Date": "পরিশোধের শেষ তারিখ",
    "Receipt / Action": "রসিদ / করণীয়",
    "Purchase receipt": "কেনাকাটার রসিদ",
    "Repay from Wallet": "ওয়ালেট থেকে পরিশোধ করুন",
    "Repayment receipt": "পরিশোধের রসিদ",
    "No deferred purchases yet.": "পরে পরিশোধের কোনো কেনাকাটা এখনও নেই।",
    "Repaid": "পরিশোধ হয়েছে",
    "Deferred": "পরে পরিশোধযোগ্য",
    "DEFERRED": "পরে পরিশোধযোগ্য",
    "This deferred record has no completed wallet deduction or credit.": "পরে পরিশোধযোগ্য এই রেকর্ডে ওয়ালেট থেকে টাকা কাটা বা যোগ করা হয়নি।",
    "Processing": "প্রক্রিয়া চলছে",
    "Pay Later Purchase": "পরে পরিশোধের কেনাকাটা",
    "Pay Later Repayment": "পরে পরিশোধের টাকা দেওয়া",
    "Choose a listed demo merchant.": "তালিকা থেকে ডেমো দোকান বেছে নিন।",
    "Choose 7, 14 or 30 days to repay.": "পরিশোধের জন্য ৭, ১৪ বা ৩০ দিন বেছে নিন।",
    "This merchant invoice already has a Pay Later record.": "এই দোকানের চালানটি আগে থেকেই পরে পরিশোধের তালিকায় আছে।",
    "This purchase exceeds your available demo Pay Later limit of BDT 5,000.": "এই কেনাকাটা যোগ করলে পরে পরিশোধের মোট বাকি টাকা ডেমো সীমা ৫,০০০ টাকা ছাড়িয়ে যাবে।",
    "Pay Later purchase not found.": "পরে পরিশোধের কেনাকাটা পাওয়া যায়নি।",
    "This purchase is already being repaid.": "এই কেনাকাটার টাকা পরিশোধের প্রক্রিয়া চলছে।",
    "Insufficient wallet balance to repay this purchase.": "এই কেনাকাটা পরিশোধ করার জন্য ওয়ালেটে পর্যাপ্ত ব্যালেন্স নেই।",
    "Demo purchase repaid from your wallet.": "আপনার ওয়ালেট থেকে ডেমো কেনাকাটার টাকা পরিশোধ করা হয়েছে।",
    "This purchase is already repaid. Showing the existing receipt.": "এই কেনাকাটার টাকা আগেই পরিশোধ করা হয়েছে। আগের রসিদ দেখানো হচ্ছে।",
    "Deferred demo purchase saved. Repay it by the displayed due date.": "পরে পরিশোধের ডেমো কেনাকাটা রাখা হয়েছে। দেখানো শেষ তারিখের মধ্যে পরিশোধ করুন।",
    "Demo Grocery Store": "ডেমো মুদি দোকান",
    "Demo Pharmacy": "ডেমো ওষুধের দোকান",
    "Demo Bookshop": "ডেমো বইয়ের দোকান",
    "Demo Electronics": "ডেমো ইলেকট্রনিকস দোকান",
    "Demo Clothing Store": "ডেমো পোশাকের দোকান",
    "Demo Home Essentials": "ডেমো ঘরের প্রয়োজনীয় সামগ্রী",
    "Demo Education Supplies": "ডেমো শিক্ষাসামগ্রী",
    "Demo Travel Booking": "ডেমো ভ্রমণ বুকিং",
    "Demo Restaurant": "ডেমো রেস্তোরাঁ",
    "Demo Internet Subscription": "ডেমো ইন্টারনেট সংযোগ",
    # Auto Pay and recipient checks.
    "Auto Pay & Plans": "অটো পে ও পরিকল্পনা",
    "Future payments": "ভবিষ্যতের পেমেন্ট",
    "Plan a payment": "পেমেন্টের পরিকল্পনা করুন",
    "Operation": "লেনদেনের ধরন",
    "Recipient number / Bill account": "প্রাপকের নম্বর / বিলের অ্যাকাউন্ট",
    "01944000001 or DEMO-METER-1001": "01944000001 অথবা DEMO-METER-1001",
    "Bill category (for bill payments)": "বিলের ধরন (বিল পেমেন্টের জন্য)",
    "Not a bill": "বিল নয়",
    "Operator / Authorized provider": "অপারেটর / অনুমোদিত সেবাদাতা",
    "Wallet transfer": "ওয়ালেটে টাকা পাঠানো",
    "Mobile recharge": "মোবাইল রিচার্জ",
    "Choose the matching operator or bill provider. Send Money requires a registered wallet.": "সঠিক অপারেটর বা বিলের সেবাদাতা বেছে নিন। টাকা পাঠাতে প্রাপকের নিবন্ধিত ওয়ালেট লাগবে।",
    "First payment date": "প্রথম পেমেন্টের তারিখ",
    "Repeat": "পুনরাবৃত্তি",
    "One-time payment": "একবার পেমেন্ট",
    "Payment mode": "পরিশোধের পদ্ধতি",
    "Auto Pay when due": "নির্ধারিত দিনে অটো পে",
    "Remind me": "আমাকে মনে করিয়ে দিন",
    "pay manually when due": "নির্ধারিত দিনে নিজে পরিশোধ করব",
    "Each payment is deducted only on or after its due date.": "প্রতিটি পেমেন্টের টাকা শুধু নির্ধারিত দিনে বা তার পরে কাটা হয়।",
    "Save Payment Plan": "পেমেন্ট পরিকল্পনা সংরক্ষণ করুন",
    "Keep your balance ready": "পর্যাপ্ত ব্যালেন্স রাখুন",
    "Payments are due at midnight Bangladesh time. Auto Pay runs when you use the app or the demo scheduler runs. A failed payment does not deduct balance and is recorded with its reason.": "বাংলাদেশ সময় রাত ১২টায় পেমেন্টের সময় হয়। আপনি অ্যাপ ব্যবহার করলে বা ডেমো সময়সূচি চালু হলে অটো পে চলে। পেমেন্ট ব্যর্থ হলে ব্যালেন্স কাটে না এবং ব্যর্থতার কারণ রাখা হয়।",
    "Demo recipient": "ডেমো প্রাপক",
    "Demo recipient:": "ডেমো প্রাপক:",
    "Recharge subscriber": "রিচার্জের গ্রাহক",
    "Recharge subscriber:": "রিচার্জের গ্রাহক:",
    "DESCO account": "ডেসকো অ্যাকাউন্ট",
    "DESCO account:": "ডেসকো অ্যাকাউন্ট:",
    "Planned total": "পরিকল্পিত মোট টাকা",
    "Planned total:": "পরিকল্পিত মোট টাকা:",
    "Open Report": "রিপোর্ট খুলুন",
    "Monthly savings": "মাসিক সঞ্চয়",
    "Demo Local LPG Refill": "ডেমো স্থানীয় এলপিজি রিফিল",
    "Demo Commercial LPG Supply": "ডেমো ব্যবসায়িক এলপিজি সরবরাহ",
    "Process Due Auto Pay": "সময় হওয়া অটো পে চালান",
    "Your payment plans": "আপনার পেমেন্ট পরিকল্পনা",
    "Due date": "পরিশোধের তারিখ",
    "Payment / Recipient": "পেমেন্ট / প্রাপক",
    "Mode": "পদ্ধতি",
    "Actions": "করণীয়",
    "Manual": "নিজে পরিশোধ",
    "One-time": "একবার",
    "Print / Download": "প্রিন্ট / ডাউনলোড",
    "Pay if due": "সময় হলে পরিশোধ করুন",
    "Cancel": "বাতিল করুন",
    "Transaction summary": "লেনদেনের বিবরণ",
    "No payment plans yet. Add a one-time payment or monthly Auto Pay above.": "এখনও কোনো পেমেন্ট পরিকল্পনা নেই। উপরে একবারের পেমেন্ট বা মাসিক অটো পে যোগ করুন।",
    "Choose Send Money, Mobile Recharge or Bill Payment.": "টাকা পাঠানো, মোবাইল রিচার্জ বা বিল পেমেন্ট বেছে নিন।",
    "Choose one-time or monthly payment.": "একবার বা প্রতি মাসে পেমেন্ট বেছে নিন।",
    "Note must be 255 characters or fewer.": "নোট ২৫৫ অক্ষরের মধ্যে রাখুন।",
    "Choose a valid payment date.": "পেমেন্টের সঠিক তারিখ বেছে নিন।",
    "Choose a mobile operator.": "মোবাইল অপারেটর বেছে নিন।",
    "Blocked number. This recipient cannot be scheduled.": "নম্বরটি ব্লক করা আছে। এই প্রাপকের জন্য পেমেন্টের পরিকল্পনা করা যাবে না।",
    "Not registered. Create a wallet before scheduling a transfer.": "প্রাপক নিবন্ধিত নন। পরিকল্পিত টাকা পাঠানোর আগে প্রাপকের ওয়ালেট তৈরি করতে হবে।",
    "You cannot send money to your own number.": "নিজের নম্বরে টাকা পাঠাতে পারবেন না।",
    "Scheduled payment not found.": "পরিকল্পিত পেমেন্ট পাওয়া যায়নি।",
    "Only pending or failed payments can be cancelled.": "শুধু অপেক্ষমাণ বা ব্যর্থ পেমেন্ট বাতিল করা যাবে।",
    "This payment has already been processed.": "এই পেমেন্টের প্রক্রিয়া আগেই শেষ হয়েছে।",
    "Only pending scheduled payments can be paid.": "শুধু অপেক্ষমাণ পরিকল্পিত পেমেন্ট পরিশোধ করা যাবে।",
    "This payment is not due yet. No wallet balance has been deducted.": "এই পেমেন্টের সময় এখনও হয়নি। ওয়ালেটের কোনো টাকা কাটা হয়নি।",
    "Unsupported scheduled payment type.": "এই ধরনের পরিকল্পিত পেমেন্ট সমর্থিত নয়।",
    "Scheduled payment cancelled. No balance was deducted.": "পরিকল্পিত পেমেন্ট বাতিল হয়েছে। ব্যালেন্স কাটা হয়নি।",
    "Scheduled payment completed. Its transaction summary is available in Report.": "পরিকল্পিত পেমেন্ট সম্পন্ন হয়েছে। রিপোর্টে লেনদেনের বিবরণ দেখুন।",
    "Payment could not be completed.": "পেমেন্ট সম্পন্ন করা যায়নি।",
    "Choose a supported transaction type.": "তালিকা থেকে লেনদেনের ধরন বেছে নিন।",
    "Choose a listed provider for the selected bill category.": "নির্বাচিত বিলের ধরনের জন্য তালিকাভুক্ত সেবাদাতা বেছে নিন।",
    "Blocked number. This recipient is flagged in the demo safety registry; payment is unavailable.": "নম্বরটি ব্লক করা আছে। ডেমো নিরাপত্তার তালিকায় এই প্রাপকের সতর্কতা রয়েছে; পেমেন্ট করা যাবে না।",
    "Blocked number — flagged in the demo safety registry.": "নম্বরটি ব্লক করা আছে — ডেমো নিরাপত্তার তালিকায় সতর্কতা রয়েছে।",
    "Not registered. Create a wallet before sending money.": "প্রাপক নিবন্ধিত নন। টাকা পাঠানোর আগে ওয়ালেট তৈরি করতে হবে।",
    "Not registered. You can still prepare a demo money request.": "প্রাপক নিবন্ধিত নন। তবু ডেমো টাকা চাওয়ার বার্তা তৈরি করতে পারবেন।",
    "Not registered. Demo-only payment is available; verify the number before continuing.": "প্রাপক নিবন্ধিত নন। শুধু ডেমো পেমেন্ট করা যাবে; এগোনোর আগে নম্বর যাচাই করুন।",
    "Registered recipient": "নিবন্ধিত প্রাপক",
    "Registered recipient:": "নিবন্ধিত প্রাপক:",
    "Authorizing provider": "অনুমোদিত সেবাদাতা",
    "Choose a valid date and amount to preview your payment installments. No balance is deducted when you save a plan.": "পেমেন্টের কিস্তি দেখতে সঠিক তারিখ ও টাকার পরিমাণ বেছে নিন। পরিকল্পনা সংরক্ষণের সময় ব্যালেন্স কাটা হয় না।",
    "Bill account / Payment reference": "বিলের অ্যাকাউন্ট / পেমেন্ট রেফারেন্স",
    "Recipient mobile number": "প্রাপকের মোবাইল নম্বর",
    "January": "জানুয়ারি", "February": "ফেব্রুয়ারি", "March": "মার্চ", "April": "এপ্রিল",
    "May": "মে", "June": "জুন", "July": "জুলাই", "August": "আগস্ট",
    "September": "সেপ্টেম্বর", "October": "অক্টোবর", "November": "নভেম্বর", "December": "ডিসেম্বর",
}


_CATEGORIES = {
    "Electricity": "বিদ্যুৎ", "Gas": "গ্যাস", "Internet": "ইন্টারনেট", "Water": "পানি",
    "TV Bill": "টিভি বিল", "Credit Card": "ক্রেডিট কার্ড", "Education": "শিক্ষা",
    "Traffic Fine": "ট্রাফিক জরিমানা", "Toll Payment": "টোল", "Government Payment": "সরকারি",
    "Insurance": "বিমা", "Donation": "অনুদান", "Ticket": "টিকিট", "Hotel": "হোটেল",
    "School": "স্কুল", "College": "কলেজ", "University": "বিশ্ববিদ্যালয়",
}
for english, bangla in _CATEGORIES.items():
    EXTRA_BANGLA[f"{english} Payment"] = f"{bangla} পেমেন্ট"
    EXTRA_BANGLA[f"Choose a listed provider for {english}."] = f"{bangla} পেমেন্টের জন্য তালিকা থেকে সেবাদাতা বেছে নিন।"
    EXTRA_BANGLA[f"Demo {english.lower()} payment completed and recorded in Report."] = f"ডেমো {bangla} পেমেন্ট সম্পন্ন হয়েছে এবং রিপোর্টে তথ্য রাখা হয়েছে।"

EXTRA_BANGLA.update({
    "Recharge and everyday utility or education bills.": "মোবাইল রিচার্জ এবং দৈনন্দিন সেবা ও শিক্ষার বিল পরিশোধ করুন।",
    "Manage your demo wallet, plan savings and prepare money requests.": "ডেমো ওয়ালেট ব্যবহার করুন, সঞ্চয়ের পরিকল্পনা করুন এবং টাকা চাওয়ার বার্তা তৈরি করুন।",
    "Government fees, travel, donations and your wallet records.": "সরকারি ফি, ভ্রমণ, অনুদান ও ওয়ালেটের তথ্য দেখুন।",
    "Transfer demo money to another registered wallet.": "অন্য নিবন্ধিত ওয়ালেটে ডেমো টাকা পাঠান।",
    "Recharge a Bangladeshi mobile number using demo balance.": "ডেমো ব্যালেন্স দিয়ে বাংলাদেশের মোবাইল নম্বরে রিচার্জ করুন।",
    "Withdraw demo wallet funds through an agent or ATM, with a fee preview.": "ফি আগে দেখে এজেন্ট বা এটিএমের মাধ্যমে ডেমো টাকা তুলুন।",
    "Choose a bill category and its matching provider.": "বিলের ধরন ও সঠিক সেবাদাতা বেছে নিন।",
    "Top up your wallet from a demo bank, card or transfer.": "ডেমো ব্যাংক, কার্ড বা ট্রান্সফার থেকে ওয়ালেটে টাকা যোগ করুন।",
    "Save a fixed monthly plan and estimate maturity at a demo 10% annual rate.": "নির্দিষ্ট মাসিক সঞ্চয় পরিকল্পনা রাখুন এবং ডেমো বার্ষিক ১০% হারে মেয়াদ শেষে সম্ভাব্য টাকা হিসাব করুন।",
    "Track a deferred demo purchase and repay it from your wallet.": "পরে পরিশোধের ডেমো কেনাকাটার হিসাব রাখুন এবং ওয়ালেট থেকে পরিশোধ করুন।",
    "Schedule one-time or monthly demo payments for the next two months.": "আগামী দুই মাসের একবারের বা মাসিক ডেমো পেমেন্টের পরিকল্পনা করুন।",
    "Record a demo NPSB / BEFTN bank transfer or a Visa card transfer.": "ডেমো NPSB / BEFTN ব্যাংক ট্রান্সফার বা ভিসা কার্ডে ট্রান্সফার লিখে রাখুন।",
    "Prepare a money request message to share yourself.": "নিজে পাঠানোর জন্য টাকা চাওয়ার বার্তা তৈরি করুন।",
    "Review transactions, download receipts and export filtered reports.": "লেনদেন দেখুন, রসিদ ডাউনলোড করুন এবং ফিল্টার করা রিপোর্ট নামান।",
    "Pay an electricity bill using your customer or meter number.": "গ্রাহক বা মিটার নম্বর দিয়ে বিদ্যুৎ বিল পরিশোধ করুন।",
    "Choose a gas company or LPG invoice provider and enter your customer account.": "গ্যাস কোম্পানি বা এলপিজি সরবরাহকারী বেছে নিয়ে গ্রাহক অ্যাকাউন্ট লিখুন।",
    "Record a demo broadband or internet subscription payment.": "ডেমো ব্রডব্যান্ড বা ইন্টারনেট বিলের পেমেন্ট লিখে রাখুন।",
    "Pay a water utility bill with your customer or bill number.": "গ্রাহক বা বিল নম্বর দিয়ে পানির বিল পরিশোধ করুন।",
    "Record a demo cable or satellite TV subscription payment.": "ডেমো কেবল বা স্যাটেলাইট টিভি বিলের পেমেন্ট লিখে রাখুন।",
    "Pay a demo card statement using a payment reference.": "পেমেন্ট রেফারেন্স দিয়ে ডেমো কার্ডের বিল পরিশোধ করুন।",
    "Choose education fees or open the dedicated School, College and University services.": "শিক্ষা ফি বেছে নিন অথবা স্কুল, কলেজ ও বিশ্ববিদ্যালয়ের আলাদা সেবা খুলুন।",
    "Pay a demo traffic fine using its case reference.": "মামলার রেফারেন্স দিয়ে ডেমো ট্রাফিক জরিমানা পরিশোধ করুন।",
    "Record a bridge or expressway toll payment.": "সেতু বা এক্সপ্রেসওয়ের টোল পেমেন্ট লিখে রাখুন।",
    "Record a government fee or tax payment with its reference.": "রেফারেন্স দিয়ে সরকারি ফি বা করের পেমেন্ট লিখে রাখুন।",
    "Record a demo insurance premium payment.": "ডেমো বিমার প্রিমিয়াম পেমেন্ট লিখে রাখুন।",
    "Record a demo donation to a community or relief campaign.": "স্থানীয় সহায়তা বা ত্রাণে ডেমো অনুদান লিখে রাখুন।",
    "Pay for an existing demo transport or event booking.": "আগে করা ডেমো যাতায়াত বা অনুষ্ঠানের বুকিং পরিশোধ করুন।",
    "Record payment for an existing demo hotel reservation.": "আগে করা ডেমো হোটেল বুকিংয়ের পেমেন্ট লিখে রাখুন।",
})
for english, bangla in (("school", "স্কুল"), ("college", "কলেজ"), ("university", "বিশ্ববিদ্যালয়")):
    EXTRA_BANGLA[f"Pay demo {english} admission, tuition or examination fees."] = f"ডেমো {bangla} ভর্তি, বেতন বা পরীক্ষার ফি দিন।"
    EXTRA_BANGLA[f"Demo {english.title()}"] = f"ডেমো {bangla}"
    for city, translated_city in (("Dhaka", "ঢাকা"), ("Chattogram", "চট্টগ্রাম"), ("Rajshahi", "রাজশাহী"), ("Sylhet", "সিলেট"), ("Khulna", "খুলনা"), ("Rangpur", "রংপুর"), ("Barishal", "বরিশাল"), ("Cumilla", "কুমিল্লা"), ("Mymensingh", "ময়মনসিংহ")):
        EXTRA_BANGLA[f"Demo {city} {english.title()}"] = f"ডেমো {translated_city} {bangla}"

EXTRA_BANGLA.update({
    "Demo Broadband": "ডেমো ব্রডব্যান্ড", "Demo Fiber Internet": "ডেমো ফাইবার ইন্টারনেট",
    "Demo Rural Broadband": "ডেমো গ্রামীণ ব্রডব্যান্ড", "Demo Business Internet": "ডেমো ব্যবসায়িক ইন্টারনেট",
    "Demo Dhaka North Electricity": "ডেমো ঢাকা উত্তর বিদ্যুৎ", "Demo Dhaka South Electricity": "ডেমো ঢাকা দক্ষিণ বিদ্যুৎ",
    "Demo Rural Electricity": "ডেমো গ্রামীণ বিদ্যুৎ", "Demo Water Utility": "ডেমো পানির সেবা",
    "Demo Cable TV": "ডেমো কেবল টিভি", "Demo Satellite TV": "ডেমো স্যাটেলাইট টিভি",
    "Demo Digital TV": "ডেমো ডিজিটাল টিভি", "Demo Family TV Package": "ডেমো পরিবার টিভি প্যাকেজ",
    "Demo Premium TV Package": "ডেমো বিশেষ টিভি প্যাকেজ",
    "Demo Bank Credit Card": "ডেমো ব্যাংক ক্রেডিট কার্ড", "Demo Classic Card": "ডেমো সাধারণ কার্ড",
    "Demo Gold Card": "ডেমো গোল্ড কার্ড", "Demo Platinum Card": "ডেমো প্লাটিনাম কার্ড",
    "Demo Student Card": "ডেমো শিক্ষার্থী কার্ড", "Demo Corporate Card": "ডেমো প্রতিষ্ঠানের কার্ড",
    "Demo Travel Card": "ডেমো ভ্রমণ কার্ড", "Demo Shopping Card": "ডেমো কেনাকাটার কার্ড",
    "Demo Rewards Card": "ডেমো পুরস্কার কার্ড", "Demo Secured Card": "ডেমো জামানতভিত্তিক কার্ড",
    "Demo School Admission": "ডেমো স্কুল ভর্তি", "Demo School Tuition": "ডেমো স্কুলের বেতন",
    "Demo College Admission": "ডেমো কলেজ ভর্তি", "Demo College Tuition": "ডেমো কলেজের বেতন",
    "Demo University Admission": "ডেমো বিশ্ববিদ্যালয়ে ভর্তি", "Demo University Tuition": "ডেমো বিশ্ববিদ্যালয়ের বেতন",
    "Demo Examination Fees": "ডেমো পরীক্ষার ফি",
    "Demo Traffic Authority": "ডেমো ট্রাফিক বিভাগ", "Demo Highway Traffic Fine": "ডেমো মহাসড়কের ট্রাফিক জরিমানা",
    "Demo Vehicle Violation": "ডেমো গাড়ির নিয়ম ভাঙার জরিমানা",
    "Demo Bridge Toll": "ডেমো সেতুর টোল", "Demo Expressway Toll": "ডেমো এক্সপ্রেসওয়ের টোল",
    "Demo River Bridge Toll": "ডেমো নদীর সেতুর টোল", "Demo City Expressway Toll": "ডেমো শহরের এক্সপ্রেসওয়ে টোল",
    "Demo Highway Toll": "ডেমো মহাসড়কের টোল", "Demo Tunnel Toll": "ডেমো সুড়ঙ্গের টোল",
    "Demo Truck Toll": "ডেমো ট্রাকের টোল", "Demo Bus Toll": "ডেমো বাসের টোল",
    "Demo Private Car Toll": "ডেমো ব্যক্তিগত গাড়ির টোল", "Demo Toll Pass Renewal": "ডেমো টোল পাস নবায়ন",
    "Demo Government Fee": "ডেমো সরকারি ফি", "Demo Tax Payment": "ডেমো কর পরিশোধ",
    "Demo Passport Fee": "ডেমো পাসপোর্ট ফি", "Demo Birth Registration": "ডেমো জন্ম নিবন্ধন",
    "Demo Trade License": "ডেমো ব্যবসার লাইসেন্স", "Demo Driving License": "ডেমো গাড়ি চালানোর লাইসেন্স",
    "Demo Vehicle Registration": "ডেমো গাড়ির নিবন্ধন", "Demo Land Service Fee": "ডেমো ভূমি সেবার ফি",
    "Demo Application Fee": "ডেমো আবেদন ফি", "Demo Treasury Challan": "ডেমো সরকারি চালান",
    "Demo Life Insurance": "ডেমো জীবনবিমা", "Demo General Insurance": "ডেমো সাধারণ বিমা",
    "Demo Health Insurance": "ডেমো স্বাস্থ্যবিমা", "Demo Motor Insurance": "ডেমো গাড়ির বিমা",
    "Demo Home Insurance": "ডেমো বাড়ির বিমা", "Demo Travel Insurance": "ডেমো ভ্রমণবিমা",
    "Demo Education Insurance": "ডেমো শিক্ষা বিমা", "Demo Accident Insurance": "ডেমো দুর্ঘটনার বিমা",
    "Demo Family Insurance": "ডেমো পরিবার বিমা", "Demo Business Insurance": "ডেমো ব্যবসার বিমা",
    "Demo Community Fund": "ডেমো এলাকার সহায়তা তহবিল", "Demo Relief Fund": "ডেমো ত্রাণ তহবিল",
    "Demo Education Fund": "ডেমো শিক্ষা তহবিল", "Demo Healthcare Fund": "ডেমো চিকিৎসা তহবিল",
    "Demo Food Assistance": "ডেমো খাদ্য সহায়তা", "Demo Flood Relief": "ডেমো বন্যার ত্রাণ",
    "Demo Winter Support": "ডেমো শীতকালীন সহায়তা", "Demo Orphan Support": "ডেমো এতিমদের সহায়তা",
    "Demo Disability Support": "ডেমো প্রতিবন্ধী ব্যক্তিদের সহায়তা", "Demo Clean Water Fund": "ডেমো বিশুদ্ধ পানির তহবিল",
    "Demo Transport Tickets": "ডেমো যাতায়াতের টিকিট", "Demo Event Tickets": "ডেমো অনুষ্ঠানের টিকিট",
    "Demo Bus Booking": "ডেমো বাস বুকিং", "Demo Train Booking": "ডেমো ট্রেন বুকিং",
    "Demo Ferry Booking": "ডেমো ফেরি বুকিং", "Demo Flight Booking": "ডেমো বিমানের বুকিং",
    "Demo Cinema Booking": "ডেমো সিনেমার বুকিং", "Demo Concert Booking": "ডেমো সংগীতানুষ্ঠানের বুকিং",
    "Demo Sports Event": "ডেমো খেলাধুলার অনুষ্ঠান", "Demo Museum Ticket": "ডেমো জাদুঘরের টিকিট",
    "Demo Hotel Booking": "ডেমো হোটেল বুকিং", "Demo Resort Booking": "ডেমো অবকাশকেন্দ্রের বুকিং",
    "Demo Guest House Booking": "ডেমো অতিথিশালার বুকিং", "Demo Coxs Bazar Hotel": "ডেমো কক্সবাজার হোটেল",
})
for city, translated_city in (("Dhaka", "ঢাকা"), ("Chattogram", "চট্টগ্রাম"), ("Rajshahi", "রাজশাহী"), ("Sylhet", "সিলেট"), ("Khulna", "খুলনা"), ("Rangpur", "রংপুর"), ("Barishal", "বরিশাল"), ("Cumilla", "কুমিল্লা"), ("Mymensingh", "ময়মনসিংহ")):
    for service, translated_service in (("Electricity", "বিদ্যুৎ"), ("Internet", "ইন্টারনেট"), ("Water", "পানি"), ("Cable", "কেবল টিভি"), ("Traffic Fine", "ট্রাফিক জরিমানা"), ("Hotel", "হোটেল")):
        EXTRA_BANGLA[f"Demo {city} {service}"] = f"ডেমো {translated_city} {translated_service}"
