"""Bangla interface copy for transparent, read-only wallet insights."""

INSIGHTS_BANGLA = {
    "Financial Health": "আর্থিক অবস্থা",
    "Financial Health Center": "আর্থিক অবস্থার কেন্দ্র",
    "Explainable wallet planning": "ব্যাখ্যাসহ ওয়ালেট পরিকল্পনা",
    "Open Financial Health": "আর্থিক অবস্থা দেখুন",
    "See what is left after upcoming payments, verify your ledger and review unusual activity.": "আসন্ন পেমেন্টের পরে কত থাকবে দেখুন, লেনদেনের হিসাব মিলিয়ে নিন এবং অস্বাভাবিক কার্যক্রম পর্যালোচনা করুন।",
    "Your wallet, upcoming commitments and receipt checks in one place.": "আপনার ওয়ালেট, আসন্ন পেমেন্ট ও রসিদ যাচাই এক জায়গায়।",
    "Open 30-day Report": "৩০ দিনের রিপোর্ট দেখুন",
    "Next 7 days + overdue": "পরবর্তী ৭ দিন ও বকেয়া",
    "Safe-to-spend estimate": "ব্যয়যোগ্য অর্থের হিসাব",
    "Wallet balance minus recorded commitments due soon.": "ওয়ালেটের ব্যালেন্স থেকে শিগগির পরিশোধযোগ্য নথিভুক্ত পেমেন্ট বাদ দেওয়া হয়েছে।",
    "Scheduled commitments": "নির্ধারিত পেমেন্টের সংরক্ষণ",
    "Pay Later due": "পে লেটারের পরিশোধযোগ্য অর্থ",
    "After commitments": "পেমেন্টের পরে অবশিষ্ট",
    "Funding gap": "অর্থের ঘাটতি",
    "more is needed to cover these commitments. Review due dates or add demo money.": "আরও প্রয়োজন। নির্ধারিত তারিখ পর্যালোচনা করুন অথবা ডেমো অর্থ যোগ করুন।",
    "Incomplete fee estimate": "ফি হিসাব অসম্পূর্ণ",
    "An unsupported scheduled payment was reserved at its principal amount. Review its fees before spending.": "একটি অসমর্থিত নির্ধারিত পেমেন্টের মূল অর্থ সংরক্ষণ করা হয়েছে। খরচের আগে এর ফি যাচাই করুন।",
    "Planning estimate from this demo wallet only. Unrecorded expenses and future fees are not included. This page never moves money or blocks payments.": "এই ডেমো ওয়ালেটের তথ্য দিয়ে পরিকল্পনার হিসাব। অনথিভুক্ত খরচ ও ভবিষ্যৎ ফি অন্তর্ভুক্ত নয়। এই পৃষ্ঠা অর্থ সরায় না বা পেমেন্ট আটকে দেয় না।",
    "Reserve before spending": "খরচের আগে সংরক্ষণ করুন",
    "Upcoming commitments": "আসন্ন পরিশোধ",
    "recorded commitments": "নথিভুক্ত পরিশোধ",
    "overdue": "বকেয়া",
    "Manual payment": "নিজে করা পেমেন্ট",
    "No commitments due soon": "শিগগির পরিশোধযোগ্য পেমেন্ট নেই",
    "Schedules and Pay Later amounts due in this window will appear here.": "এই সময়ের মধ্যে পরিশোধযোগ্য নির্ধারিত পেমেন্ট ও পে লেটারের অর্থ এখানে দেখাবে।",
    "Review Pay Later": "পে লেটার পর্যালোচনা করুন",
    "Observed, not predicted": "নথিভুক্ত তথ্য, পূর্বাভাস নয়",
    "Last 30 days": "গত ৩০ দিন",
    "successful entries": "সফল লেনদেন",
    "Incoming money": "আগত অর্থ",
    "Money out including fees": "ফিসহ বহির্গত অর্থ",
    "Net wallet flow": "ওয়ালেটের নিট পরিবর্তন",
    "Daily money-out average": "দৈনিক বহির্গত অর্থের গড়",
    "The daily average divides successful money out by 30 calendar days, including days without activity. Incoming transfers and top-ups are wallet inflows, not salary estimates.": "সফল বহির্গত অর্থকে লেনদেনবিহীন দিনসহ ৩০ দিন দিয়ে ভাগ করে দৈনিক গড় করা হয়। আগত ট্রান্সফার ও টপ-আপ ওয়ালেটে আসা অর্থ, বেতনের হিসাব নয়।",
    "No successful activity in this period. Start using the demo wallet to build your history.": "এই সময়ে সফল লেনদেন নেই। লেনদেনের ইতিহাস তৈরি করতে ডেমো ওয়ালেট ব্যবহার করুন।",
    "Check the arithmetic": "হিসাব মিলিয়ে নিন",
    "Ledger reconciliation": "লেনদেনের হিসাব যাচাই",
    "Matched to opening anchor": "প্রারম্ভিক হিসাবের সঙ্গে মিলেছে",
    "Difference to review": "পার্থক্য পর্যালোচনা করুন",
    "Opening anchor unavailable": "প্রারম্ভিক হিসাব পাওয়া যায়নি",
    "Recorded opening balance": "নথিভুক্ত প্রারম্ভিক ব্যালেন্স",
    "Successful incoming": "সফল আগত অর্থ",
    "Successful outgoing + fees": "সফল বহির্গত অর্থ ও ফি",
    "Expected wallet balance": "হিসাব অনুযায়ী ব্যালেন্স",
    "Current minus expected": "বর্তমান ও হিসাবকৃত ব্যালেন্সের পার্থক্য",
    "non-success entries excluded": "অসম্পন্ন লেনদেন বাদ দেওয়া হয়েছে",
    "pre-anchor entries excluded": "প্রারম্ভিক হিসাবের আগের লেনদেন বাদ দেওয়া হয়েছে",
    "Opening anchor recorded": "প্রারম্ভিক হিসাব নথিভুক্ত",
    "The comparison uses the recorded opening balance and every successful ledger entry since that instant.": "এই তুলনায় নথিভুক্ত প্রারম্ভিক ব্যালেন্স ও তারপরের সব সফল লেনদেন ব্যবহৃত হয়।",
    "Opening anchor source": "প্রারম্ভিক হিসাবের উৎস",
    "A trusted opening balance has not been recorded for this account. Reconciliation cannot verify the current balance yet.": "এই অ্যাকাউন্টের নির্ভরযোগ্য প্রারম্ভিক ব্যালেন্স নথিভুক্ত নেই। তাই বর্তমান ব্যালেন্স এখনও যাচাই করা যায় না।",
    "Review receipts": "রসিদ পর্যালোচনা করুন",
    "Activity review signals": "লেনদেন পর্যালোচনার সংকেত",
    "signals in the last 7 days": "গত ৭ দিনের সংকেত",
    "These transparent rules highlight receipts to inspect. A signal does not mean fraud or an accidental duplicate.": "এই স্পষ্ট নিয়মগুলো যাচাইয়ের জন্য রসিদ চিহ্নিত করে। সংকেত মানেই প্রতারণা বা ভুলে দুইবার পেমেন্ট নয়।",
    "Larger than your usual payment": "আপনার সাধারণ পেমেন্টের চেয়ে বড়",
    "Similar payments close together": "অল্প সময়ে একই ধরনের পেমেন্ট",
    "Previous 30-day median for this service": "এই সেবার আগের ৩০ দিনের মধ্যক",
    "earlier payments": "আগের পেমেন্ট",
    "This amount exceeds both 3× that median and BDT 1,000.": "এই অর্থ মধ্যকের ৩ গুণ ও ১,০০০ টাকা—উভয় সীমা অতিক্রম করেছে।",
    "Same service, recipient, amount and fee, with two successful receipts within 10 minutes.": "একই সেবা, প্রাপক, অর্থ ও ফি; ১০ মিনিটের মধ্যে দুটি সফল রসিদ।",
    "Inspect receipt": "রসিদ যাচাই করুন",
    "Compare earlier receipt": "আগের রসিদের সঙ্গে তুলনা করুন",
    "No review signals from these rules": "এই নিয়মে পর্যালোচনার সংকেত নেই",
    "Small histories may not have enough earlier payments for a meaningful comparison.": "ছোট লেনদেনের ইতিহাসে তুলনার জন্য যথেষ্ট আগের পেমেন্ট নাও থাকতে পারে।",
    "Showing the 8 most recent signals. Review your full Report for more activity.": "সর্বশেষ ৮টি সংকেত দেখানো হচ্ছে। আরও লেনদেনের জন্য পুরো রিপোর্ট পর্যালোচনা করুন।",
    "How this estimate works": "এই হিসাব যেভাবে কাজ করে",
    "Reserve unpaid schedules due by the end of this seven-day window, including overdue and failed items. Both automatic and manual plans count. Completed, cancelled and successfully linked payments are excluded.": "এই সাত দিনের মধ্যে পরিশোধযোগ্য অপরিশোধিত, বকেয়া ও ব্যর্থ নির্ধারিত পেমেন্ট সংরক্ষণ করা হয়। স্বয়ংক্রিয় ও নিজে করা উভয় পরিকল্পনা গণনা হয়। সম্পন্ন, বাতিল ও সফল লেনদেনের সঙ্গে যুক্ত পেমেন্ট বাদ যায়।",
    "Reserve outstanding Pay Later purchases due in this window or earlier. Repaid purchases and successfully linked repayments are excluded. Later obligations remain in Pay Later.": "এই সময়ে বা আগে পরিশোধযোগ্য পে লেটার সংরক্ষণ করা হয়। পরিশোধিত ও সফল পরিশোধের সঙ্গে যুক্ত ক্রয় বাদ যায়। পরের দায়গুলো পে লেটারে থাকে।",
    "Supported schedules are Send Money, Mobile Recharge and Bill Payment. Their current demo fee is zero. Pay Later repayment also has zero demo fee.": "সমর্থিত নির্ধারিত সেবা হলো টাকা পাঠানো, মোবাইল রিচার্জ ও বিল পেমেন্ট। এগুলোর বর্তমান ডেমো ফি শূন্য। পে লেটার পরিশোধের ডেমো ফিও শূন্য।",
    "Safe-to-spend is the wallet balance minus those reserves, with a minimum of zero. A negative remainder appears as a funding gap. Saved savings calculators do not reserve or debit money.": "ব্যয়যোগ্য অর্থ হলো ওয়ালেট ব্যালেন্স থেকে সংরক্ষিত অর্থ বাদ দেওয়ার পর অবশিষ্ট, সর্বনিম্ন শূন্য। ঋণাত্মক অবশিষ্টকে ঘাটতি হিসেবে দেখায়। সংরক্ষিত সঞ্চয় ক্যালকুলেটর অর্থ সংরক্ষণ বা কাটে না।",
    "Unusual-payment comparisons require at least five earlier successful payments of the same service type within 30 days. Failed, pending and deferred ledger entries do not affect observed cash flow or the reconciliation.": "অস্বাভাবিক পেমেন্ট তুলনার জন্য ৩০ দিনের মধ্যে একই সেবার অন্তত পাঁচটি আগের সফল পেমেন্ট লাগে। ব্যর্থ, অপেক্ষমান ও স্থগিত লেনদেন অর্থপ্রবাহ বা হিসাব যাচাইয়ে প্রভাব ফেলে না।",
    "Review your safe-to-spend estimate, upcoming commitments, ledger reconciliation and receipt signals.": "ব্যয়যোগ্য অর্থের হিসাব, আসন্ন পরিশোধ, লেনদেনের হিসাব ও রসিদের সংকেত পর্যালোচনা করুন।",
}
