"""Bangla copy for account assistance and filtered report analytics."""

ASSISTANT_BANGLA = {
    "App Assistant": "অ্যাপ সহকারী",
    "AI app assistant": "AI অ্যাপ সহকারী",
    "Local app guide": "স্থানীয় অ্যাপ সহকারী",
    "App guide": "অ্যাপ সহকারী",
    "Your wallet guide": "আপনার ওয়ালেট সহকারী",
    "Demo wallet": "ডেমো ওয়ালেট",
    "Local app guide · works without an AI connection": "স্থানীয় অ্যাপ সহকারী · AI সংযোগ ছাড়াও চলে",
    "Get help with this app and insights from your own demo wallet activity.": "অ্যাপ ব্যবহারের সাহায্য এবং আপনার নিজের ডেমো ওয়ালেটের বিশ্লেষণ পান।",
    "Your questions and account totals are sent to the configured AI provider. Do not include passwords or OTPs.": "আপনার প্রশ্ন ও অ্যাকাউন্টের মোট হিসাব নির্ধারিত AI প্রদানকারীর কাছে যায়। পাসওয়ার্ড বা OTP দেবেন না।",
    "Answers use app guidance and your account totals. Free-form AI answers need a configured provider.": "উত্তর অ্যাপের নির্দেশনা ও আপনার হিসাব থেকে আসে। মুক্তভাবে AI উত্তর পেতে প্রদানকারীর সংযোগ লাগবে।",
    "The assistant provides guidance; confirm payments in the app forms.": "সহকারী শুধু নির্দেশনা দেয়; পেমেন্ট অ্যাপের ফর্মে নিশ্চিত করুন।",
    "Questions and account totals go to the configured AI provider. Avoid passwords and OTPs.": "প্রশ্ন ও আপনার অ্যাকাউন্টের মোট হিসাব নির্ধারিত AI প্রদানকারীর কাছে যায়। পাসওয়ার্ড বা OTP দেবেন না।",
    "Uses app guidance and your wallet totals. Free-form AI answers need a configured provider.": "অ্যাপের নির্দেশনা ও আপনার ওয়ালেটের হিসাব থেকে উত্তর দেয়। মুক্তভাবে AI উত্তর পেতে প্রদানকারীর সংযোগ লাগবে।",
    "I can help you understand spending, check recipients, plan Auto Pay and download reports. All balances and activity in this prototype are demo data.": "আমি খরচ বুঝতে, প্রাপক যাচাই করতে, Auto Pay পরিকল্পনা ও রিপোর্ট নামাতে সাহায্য করি। এই অ্যাপের ব্যালেন্স ও লেনদেন ডেমো তথ্য।",
    "Ask about your balance, spending, payments, savings or transfers. Follow-up questions stay in your own account conversation.": "ব্যালেন্স, খরচ, পেমেন্ট, সঞ্চয় বা ট্রান্সফার নিয়ে প্রশ্ন করুন। পরের প্রশ্নও আপনার নিজের অ্যাকাউন্টের কথোপকথনে থাকে।",
    "Assistant conversation": "সহকারীর কথোপকথন",
    "You": "আপনি",
    "Question": "প্রশ্ন",
    "Ask Assistant": "সহকারীকে জিজ্ঞেস করুন",
    "Clear chat": "কথোপকথন মুছুন",
    "Chat cleared.": "কথোপকথন মুছে ফেলা হয়েছে।",
    "What did I spend this month?": "এই মাসে কত খরচ করেছি?",
    "How do I set up Auto Pay?": "Auto Pay কীভাবে চালু করব?",
    "How do I export my report?": "আমার রিপোর্ট কীভাবে নামাব?",
    "Spending insights": "খরচের বিশ্লেষণ",
    "Plan Auto Pay": "Auto Pay পরিকল্পনা",
    "Export Report": "রিপোর্ট নামান",
    "Suggested questions": "প্রস্তাবিত প্রশ্ন",
    "Question about this app": "অ্যাপ সম্পর্কে প্রশ্ন",
    "Ask about your wallet or this app...": "আপনার ওয়ালেট বা অ্যাপ নিয়ে প্রশ্ন করুন...",
    "Guidance only. Confirm payments in the app.": "শুধু নির্দেশনা। পেমেন্ট অ্যাপে নিশ্চিত করুন।",
    "Send": "পাঠান",
    "Sending...": "পাঠানো হচ্ছে...",
    "Reading your app information...": "আপনার অ্যাকাউন্টের তথ্য দেখা হচ্ছে...",
    "The assistant timed out. Your question is saved below; try again.": "সহকারীর উত্তর পেতে সময় শেষ। প্রশ্ন নিচে আছে; আবার চেষ্টা করুন।",
    "Close assistant": "সহকারী বন্ধ করুন",
    "Filtered account insights": "ফিল্টার করা হিসাবের বিশ্লেষণ",
    "Your activity at a glance": "এক নজরে আপনার লেনদেন",
    "successful transactions": "সফল লেনদেন",
    "All charts use the date, type, direction, status and search filters above. Money out includes fees. Failed and pending records are excluded.": "সব চার্টে উপরের তারিখ, ধরন, দিক, স্ট্যাটাস ও সার্চ ফিল্টার প্রযোজ্য। টাকা বের হওয়ার হিসাবে ফি আছে। ব্যর্থ ও অপেক্ষমাণ রেকর্ড বাদ।",
    "Net wallet change": "ওয়ালেটের নিট পরিবর্তন",
    "Change in this selection, not your current balance": "এই সময়ের পরিবর্তন; বর্তমান ব্যালেন্স নয়",
    "Largest outgoing category": "সবচেয়ে বড় খরচের বিভাগ",
    "of money out": "মোট বের হওয়া টাকার",
    "Average money out": "গড় বের হওয়া টাকা",
    "successful outgoing transactions": "সফল বহির্গামী লেনদেন",
    "Money in and out": "টাকা আসা ও বের হওয়া",
    "Bar chart by Bangladesh date; long periods are grouped.": "বাংলাদেশ সময়ের তারিখে বার চার্ট; দীর্ঘ সময় ভাগে দেখানো হয়।",
    "Money in and money out bar chart": "টাকা আসা ও বের হওয়ার বার চার্ট",
    "Money in": "টাকা এসেছে",
    "Money out": "টাকা বের হয়েছে",
    "Cumulative activity": "ক্রমযোজিত লেনদেন",
    "Running totals within your filtered selection; starts at zero.": "নির্বাচিত সময়ের ক্রমযোজিত মোট; শূন্য থেকে শুরু।",
    "Cumulative money in, money out and net change graph": "টাকা আসা, বের হওয়া ও নিট পরিবর্তনের ক্রমযোজিত গ্রাফ",
    "Net change": "নিট পরিবর্তন",
    "Spending by category": "বিভাগভিত্তিক খরচ",
    "Pie chart of successful money out, including fees.": "ফিসহ সফলভাবে বের হওয়া টাকার পাই চার্ট।",
    "Spending category pie chart": "খরচের বিভাগভিত্তিক পাই চার্ট",
    "Cumulative histogram": "ক্রমযোজিত হিস্টোগ্রাম",
    "Bars count money-out amounts in BDT bands. The line shows the cumulative share.": "বারে অঙ্কের সীমায় বহির্গামী লেনদেনের সংখ্যা। রেখায় ক্রমযোজিত শতাংশ।",
    "Money out amount histogram with cumulative percentage": "বহির্গামী অঙ্কের হিস্টোগ্রাম ও ক্রমযোজিত শতাংশ",
    "Transaction count": "লেনদেনের সংখ্যা",
    "Cumulative percentage": "ক্রমযোজিত শতাংশ",
    "View chart data": "চার্টের তথ্য দেখুন",
    "Date (BD)": "তারিখ (বাংলাদেশ)",
    "Cumulative net change": "ক্রমযোজিত নিট পরিবর্তন",
    "Amount band (BDT)": "অঙ্কের সীমা (টাকা)",
    "No successful money out matches these filters.": "এই ফিল্টারে কোনো সফল বহির্গামী লেনদেন নেই।",
    "No successful transactions match these filters. Change the date or other filters to analyze your activity.": "এই ফিল্টারে সফল লেনদেন নেই। বিশ্লেষণের জন্য তারিখ বা অন্য ফিল্টার বদলান।",
    "Bank Transfer": "ব্যাংক ট্রান্সফার",
    "Visa Transfer": "ভিসা ট্রান্সফার",
    "Bill Payment": "বিল পেমেন্ট",
    "Mobile Recharge": "মোবাইল রিচার্জ",
    "Send Money": "টাকা পাঠান",
    "Cash Out": "ক্যাশ আউট",
    "Pay Later Repayment": "পে লেটার পরিশোধ",
    "Send a question as an object.": "প্রশ্ন সঠিক ফরম্যাটে পাঠান।",
    "Enter a question about the app.": "অ্যাপ সম্পর্কে একটি প্রশ্ন লিখুন।",
    "Keep your question within 1,200 characters.": "প্রশ্ন ১,২০০ অক্ষরের মধ্যে রাখুন।",
    "The conversation is too long. Start a new chat.": "কথোপকথন বেশি বড় হয়েছে। নতুন কথোপকথন শুরু করুন।",
    "Invalid conversation history.": "কথোপকথনের ইতিহাস সঠিক নয়।",
    "Invalid conversation message.": "কথোপকথনের বার্তা সঠিক নয়।",
    "Please wait a minute before asking more questions.": "আরও প্রশ্ন করার আগে এক মিনিট অপেক্ষা করুন।",
    "Your session expired. Sign in again to use the assistant.": "সেশনের মেয়াদ শেষ। সহকারী ব্যবহার করতে আবার লগ ইন করুন।",
    "Your session token expired. Refresh this page and try again.": "সেশন টোকেনের মেয়াদ শেষ। পাতা রিফ্রেশ করে আবার চেষ্টা করুন।",
    "The assistant is unavailable. Try again shortly.": "সহকারী এখন পাওয়া যাচ্ছে না। কিছুক্ষণ পরে আবার চেষ্টা করুন।",
    "The assistant could not answer. Try again.": "সহকারী উত্তর দিতে পারেনি। আবার চেষ্টা করুন।",
    "Unable to load chat. Refresh and try again.": "কথোপকথন লোড করা যায়নি। রিফ্রেশ করে আবার চেষ্টা করুন।",
    "Unable to clear chat. Refresh and try again.": "কথোপকথন মুছে ফেলা যায়নি। রিফ্রেশ করে আবার চেষ্টা করুন।",
    "Answered using your own demo account information.": "আপনার নিজের ডেমো অ্যাকাউন্টের তথ্য থেকে উত্তর দেওয়া হয়েছে।",
}
