"""Bangla disclosures for account sessions and separate AI consent purposes."""

SECURITY_BANGLA = {
    "Privacy & AI": "গোপনীয়তা ও AI",
    "Your choice": "আপনার সিদ্ধান্ত",
    "Control your AI data and choose how your wallet information is used.": "আপনার AI তথ্য নিয়ন্ত্রণ করুন এবং ওয়ালেটের তথ্য কীভাবে ব্যবহার হবে তা বেছে নিন।",
    "Privacy receipt": "গোপনীয়তার অনুরোধের রসিদ",
    "Your request has been completed.": "আপনার অনুরোধ সম্পন্ন হয়েছে।",
    "Hosted AI consent is disabled after erasing AI data. Wallet transactions remain available for your receipts and reports.": "AI তথ্য মুছে দিলে হোস্টেড AI ব্যবহারের সম্মতিও বন্ধ হয়। রসিদ ও রিপোর্টের জন্য ওয়ালেটের লেনদেনের তথ্য সংরক্ষিত থাকে।",
    "Hosted AI assistant": "হোস্টেড AI সহকারী",
    "Local app guidance works without sending your information to an AI provider. Hosted AI is optional and off by default.": "স্থানীয় অ্যাপ নির্দেশনায় AI সেবাদাতাকে আপনার তথ্য পাঠানো হয় না। হোস্টেড AI ঐচ্ছিক এবং শুরুতে বন্ধ থাকে।",
    "When enabled, the configured OpenAI provider receives your redacted question, up to eight recent chat messages, wallet balance, spending totals and upcoming payment amounts. Profile, recipient, invoice and transaction notes are excluded. Redaction cannot detect every private detail, so never include passwords, OTPs or PINs.": "চালু করলে নির্ধারিত OpenAI সেবাদাতার কাছে সংবেদনশীল তথ্য আড়াল করা প্রশ্ন, সর্বোচ্চ আটটি সাম্প্রতিক চ্যাট বার্তা, ওয়ালেট ব্যালেন্স, মোট খরচ ও আসন্ন পেমেন্টের পরিমাণ পাঠানো হয়। প্রোফাইল, প্রাপক, ইনভয়েস ও লেনদেনের নোট পাঠানো হয় না। সব ব্যক্তিগত তথ্য শনাক্ত করে আড়াল করা সম্ভব নয়; তাই পাসওয়ার্ড, ওটিপি বা পিন লিখবেন না।",
    "The assistant gives guidance. It cannot execute a payment, change your wallet or choose actions for you. App forms require your confirmation.": "সহকারী নির্দেশনা দেয়। এটি পেমেন্ট করতে, ওয়ালেট পরিবর্তন করতে বা আপনার হয়ে সিদ্ধান্ত নিতে পারে না। অ্যাপের ফর্মে আপনার নিশ্চিতকরণ লাগে।",
    "Hosted AI is enabled for your account.": "আপনার অ্যাকাউন্টে হোস্টেড AI চালু আছে।",
    "Disable hosted AI and erase chat": "হোস্টেড AI বন্ধ করে চ্যাট মুছুন",
    "I understand this disclosure and choose to share the listed data with the hosted AI provider for answers.": "আমি এই বিবরণ বুঝেছি এবং উত্তর পাওয়ার জন্য উল্লিখিত তথ্য হোস্টেড AI সেবাদাতার সঙ্গে ভাগ করতে সম্মত।",
    "Enable hosted AI": "হোস্টেড AI চালু করুন",
    "Model research consent": "মডেল গবেষণার সম্মতি",
    "This choice is separate from hosted AI and pilot participation. It allows you to download daily wallet aggregates for research review. It does not automatically upload data, train a model or approve research use. Direct identifiers are excluded, but spending patterns can still be identifying.": "এই সিদ্ধান্ত হোস্টেড AI ও পাইলট অংশগ্রহণ থেকে আলাদা। গবেষণার পর্যালোচনার জন্য দৈনিক ওয়ালেটের সামগ্রিক তথ্য ডাউনলোড করা যায়। এতে স্বয়ংক্রিয়ভাবে তথ্য আপলোড, মডেল প্রশিক্ষণ বা গবেষণায় ব্যবহারের অনুমোদন হয় না। সরাসরি পরিচয়সূচক তথ্য বাদ থাকে, তবে খরচের ধরন থেকেও পরিচয় বোঝা যেতে পারে।",
    "Research export consent is enabled.": "গবেষণার তথ্য রপ্তানির সম্মতি চালু আছে।",
    "Download research aggregates": "গবেষণার সামগ্রিক তথ্য ডাউনলোড করুন",
    "Revoke research consent": "গবেষণার সম্মতি প্রত্যাহার করুন",
    "I choose to enable my own aggregate research export for review. No automatic training is authorized.": "পর্যালোচনার জন্য নিজের সামগ্রিক গবেষণা তথ্য রপ্তানি চালু করতে সম্মত। স্বয়ংক্রিয় মডেল প্রশিক্ষণের অনুমতি দিচ্ছি না।",
    "Enable research export": "গবেষণার তথ্য রপ্তানি চালু করুন",
    "Retention, export and erasure": "সংরক্ষণ, রপ্তানি ও মুছে ফেলা",
    "Chat history contains at most eight messages and expires after": "চ্যাটে সর্বোচ্চ আটটি বার্তা থাকে। ব্যবহার না করলে চ্যাটের মেয়াদ শেষ হয়",
    "days of inactivity. AI governance events contain outcome categories only and expire after 30 days. Consent remains until you revoke or erase it. The local app guide also stores bounded chat history for follow-up questions.": "দিন পরে। AI নিয়ন্ত্রণের ঘটনায় শুধু ফলাফলের ধরন থাকে এবং ৩০ দিন পরে মুছে যায়। প্রত্যাহার বা মুছে ফেলার আগে পর্যন্ত সম্মতি থাকে। পরবর্তী প্রশ্নের জন্য স্থানীয় নির্দেশিকাও সীমিত চ্যাট সংরক্ষণ করে।",
    "Clear chat removes conversation history. Erase AI data also removes your AI consents and AI governance events. Wallet ledger records are retained. Downloaded copies and provider-held data are outside this app’s deletion control; consult the provider data policy before enabling hosted AI.": "চ্যাট মুছলে কথোপকথন মুছে যায়। AI তথ্য মুছলে AI সম্মতি ও নিয়ন্ত্রণের ঘটনাও মুছে যায়। ওয়ালেটের লেনদেনের রেকর্ড থাকে। ডাউনলোড করা কপি ও সেবাদাতার কাছে থাকা তথ্য এই অ্যাপ থেকে মোছা যায় না; হোস্টেড AI চালুর আগে সেবাদাতার তথ্য নীতি দেখুন।",
    "Download my account and AI data": "আমার অ্যাকাউন্ট ও AI তথ্য ডাউনলোড করুন",
    "Erase my AI data": "আমার AI তথ্য মুছুন",
    "A content-free erasure counter remains until account deletion to prevent requests already running from recreating erased chat. It contains no question, answer or financial amount and is included in your data export.": "চলমান কোনো অনুরোধ যেন মুছে ফেলা চ্যাট আবার সংরক্ষণ না করে, সে জন্য অ্যাকাউন্ট মুছে ফেলা পর্যন্ত একটি তথ্যবিহীন মোছার গণনা রাখা হয়। এতে প্রশ্ন, উত্তর বা আর্থিক পরিমাণ থাকে না। নিজের তথ্য ডাউনলোড করলে এই গণনাও পাবেন।",
    "Consent policy": "সম্মতির নীতি",
    "Return to Assistant": "সহকারীতে ফিরে যান",
    "Hosted AI is enabled by your consent. Redacted questions, bounded chat history and account totals are sent to the configured provider.": "আপনার সম্মতিতে হোস্টেড AI চালু আছে। সংবেদনশীল তথ্য আড়াল করা প্রশ্ন, সীমিত চ্যাট ও অ্যাকাউন্টের মোট পরিমাণ নির্ধারিত সেবাদাতাকে পাঠানো হয়।",
    "AI privacy & consent": "AI গোপনীয়তা ও সম্মতি",
    "Control AI sharing, export your data and erase your chat.": "AI তথ্য ভাগ করা নিয়ন্ত্রণ করুন, নিজের তথ্য ডাউনলোড করুন এবং চ্যাট মুছুন।",
    "Privacy settings": "গোপনীয়তার সেটিংস",
    "Account security": "অ্যাকাউন্টের নিরাপত্তা",
    "Device sessions": "ডিভাইস সেশন",
    "Review and revoke verified browser sessions.": "যাচাইকৃত ব্রাউজার সেশন দেখুন ও প্রত্যাহার করুন।",
    "Manage sessions": "সেশন পরিচালনা করুন",
    "Each sign-in uses an expiring session bound to this browser. Revoke a session to require a new verification code.": "প্রতিবার সাইন ইন করলে এই ব্রাউজারের সঙ্গে যুক্ত মেয়াদযুক্ত সেশন তৈরি হয়। সেশন প্রত্যাহার করলে আবার যাচাইকরণ কোড দিতে হবে।",
    "This browser": "এই ব্রাউজার",
    "Another browser session": "অন্য ব্রাউজারের সেশন",
    "Session expires in": "সেশনের মেয়াদ শেষ হবে",
    "minutes after sign-in.": "মিনিট পরে, সাইন ইন করার সময় থেকে।",
    "Revoke session": "সেশন প্রত্যাহার করুন",
    "No verified browser sessions. Sign in again to create one.": "কোনো যাচাইকৃত ব্রাউজার সেশন নেই। নতুন সেশন তৈরি করতে আবার সাইন ইন করুন।",
    "Back to settings": "সেটিংসে ফিরে যান",
    "Read the disclosure and explicitly accept before enabling this purpose.": "এই সুবিধা চালু করার আগে বিবরণ পড়ুন এবং স্পষ্টভাবে সম্মতি দিন।",
    "Your browser session has been revoked.": "আপনার ব্রাউজার সেশন প্রত্যাহার করা হয়েছে।",
}
