"""API, security, AI governance, durable workers and query indexes. Generated from the reviewed schema on 7 October 2026."""
import os
import sqlalchemy as sa
from alembic import op

revision = '20261007_02'
down_revision = '20261007_01'
branch_labels = None
depends_on = None

def _create_table(name, *columns, **kwargs):
    inspector = sa.inspect(op.get_bind())
    if name in inspector.get_table_names():
        if os.environ.get("ALEMBIC_ADOPT_EXISTING") != "1":
            raise RuntimeError("Existing schema requires an explicit validated adoption: ALEMBIC_ADOPT_EXISTING=1")
        expected = {column.name: column for column in columns if isinstance(column, sa.Column)}
        actual = {column["name"]: column for column in inspector.get_columns(name)}
        if set(expected) != set(actual) or any(not column.primary_key and column.nullable != actual[key]["nullable"] for key, column in expected.items()):
            raise RuntimeError("Existing table is incompatible with the frozen baseline: " + name)
        frozen = sa.Table(name, sa.MetaData(), *columns)
        for key, column in expected.items():
            reflected = actual[key]["type"]
            if column.type._type_affinity is not reflected._type_affinity:
                raise RuntimeError("Incompatible existing column type: " + name + "." + key)
            for attribute in ("length", "precision", "scale"):
                if getattr(column.type, attribute, None) != getattr(reflected, attribute, None):
                    raise RuntimeError("Incompatible existing column bounds: " + name + "." + key)
        if list(frozen.primary_key.columns.keys()) != inspector.get_pk_constraint(name)["constrained_columns"]:
            raise RuntimeError("Incompatible existing primary key: " + name)
        actual_foreign = {(tuple(c["constrained_columns"]), c["referred_table"], tuple(c["referred_columns"]),
                           c.get("options", {}).get("ondelete"), c.get("options", {}).get("onupdate"))
                          for c in inspector.get_foreign_keys(name)}
        # Resolve targets from strings; referenced tables may not be loaded yet.
        expected_foreign = {(tuple(c.columns.keys()), next(iter(c.elements)).target_fullname.split(".")[-2],
                             tuple(e.target_fullname.split(".")[-1] for e in c.elements), c.ondelete, c.onupdate)
                            for c in frozen.foreign_key_constraints}
        if expected_foreign != actual_foreign:
            raise RuntimeError("Incompatible existing foreign keys: " + name)
        expected_unique = {tuple(c.columns.keys()) for c in frozen.constraints if isinstance(c, sa.UniqueConstraint)}
        actual_unique = {tuple(c["column_names"]) for c in inspector.get_unique_constraints(name)}
        if not expected_unique.issubset(actual_unique):
            raise RuntimeError("Missing existing uniqueness constraint: " + name)
        return
    op.create_table(name, *columns, **kwargs)

def _create_index(name, table_name, columns, **kwargs):
    actual = {index["name"]: index for index in sa.inspect(op.get_bind()).get_indexes(table_name)}
    if name in actual:
        if actual[name]["column_names"] != columns or actual[name]["unique"] != bool(kwargs.get("unique", False)):
            raise RuntimeError("Incompatible existing index: " + name)
        return
    op.create_index(name, table_name, columns, **kwargs)

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    _create_table('security_audit_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('result', sa.String(length=40), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_security_audit_events_action'), 'security_audit_events', ['action'], unique=False)
    _create_index(op.f('ix_security_audit_events_created_at'), 'security_audit_events', ['created_at'], unique=False)
    _create_index(op.f('ix_security_audit_events_request_id'), 'security_audit_events', ['request_id'], unique=False)
    _create_index(op.f('ix_security_audit_events_user_id'), 'security_audit_events', ['user_id'], unique=False)
    _create_table('security_rate_buckets',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.BigInteger(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('key_hash', 'category', 'window_start')
    )
    _create_index(op.f('ix_security_rate_buckets_expires_at'), 'security_rate_buckets', ['expires_at'], unique=False)
    _create_table('worker_heartbeats',
    sa.Column('worker_id', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('worker_id')
    )
    _create_table('ai_consents',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('policy_version', sa.String(length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'purpose')
    )
    _create_table('ai_conversation_retention',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_index(op.f('ix_ai_conversation_retention_expires_at'), 'ai_conversation_retention', ['expires_at'], unique=False)
    _create_table('ai_governance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_ai_governance_events_created_at'), 'ai_governance_events', ['created_at'], unique=False)
    _create_index(op.f('ix_ai_governance_events_user_id'), 'ai_governance_events', ['user_id'], unique=False)
    _create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('secret_hash')
    )
    _create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    _create_table('provider_intents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('biller_reference', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider_reference', sa.String(length=80), nullable=True),
    sa.Column('provider_sequence', sa.Integer(), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_provider_intents_user_id'), 'provider_intents', ['user_id'], unique=False)
    _create_table('security_otp_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed_at', sa.BigInteger(), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_security_otp_challenges_expires_at'), 'security_otp_challenges', ['expires_at'], unique=False)
    _create_index(op.f('ix_security_otp_challenges_user_id'), 'security_otp_challenges', ['user_id'], unique=False)
    _create_table('security_trusted_sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('revoked_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    _create_index(op.f('ix_security_trusted_sessions_expires_at'), 'security_trusted_sessions', ['expires_at'], unique=False)
    _create_index(op.f('ix_security_trusted_sessions_user_id'), 'security_trusted_sessions', ['user_id'], unique=False)
    _create_index('ix_transactions_user_status_created', 'transactions', ['user_id', 'status', 'created_at'], unique=False)
    _create_table('api_idempotency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'key', name='uq_api_token_idempotency')
    )
    _create_table('provider_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=32), nullable=True),
    sa.Column('last_error', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['provider_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id')
    )
    _create_index(op.f('ix_provider_outbox_available_at'), 'provider_outbox', ['available_at'], unique=False)
    _create_index(op.f('ix_provider_outbox_status'), 'provider_outbox', ['status'], unique=False)
    _create_table('provider_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('intent_id', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['provider_intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    _create_index('ix_schedules_due_auto_status', 'scheduled_payments', ['status', 'auto_pay', 'due_at'], unique=False)
    _create_table('transaction_review_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('rule', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'rule', name='uq_transaction_review_rule')
    )
    _create_index(op.f('ix_transaction_review_flags_rule'), 'transaction_review_flags', ['rule'], unique=False)
    _create_index(op.f('ix_transaction_review_flags_status'), 'transaction_review_flags', ['status'], unique=False)
    _create_index(op.f('ix_transaction_review_flags_transaction_id'), 'transaction_review_flags', ['transaction_id'], unique=False)
    _create_table('schedule_retries',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=80), nullable=True),
    sa.Column('exhausted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['scheduled_payments.id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    _create_index(op.f('ix_schedule_retries_next_attempt_at'), 'schedule_retries', ['next_attempt_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade disabled; restore a tested database backup instead.")
