"""Frozen original wallet baseline. Generated from the reviewed schema on 7 October 2026."""
import os
import sqlalchemy as sa
from alembic import op

revision = '20261007_01'
down_revision = None
branch_labels = None
depends_on = None

def _create_table(name, *columns, **kwargs):
    inspector = sa.inspect(op.get_bind())
    if name in inspector.get_table_names():
        if os.environ.get("ALEMBIC_ADOPT_EXISTING") != "1":
            raise RuntimeError("Existing schema requires an explicit validated adoption: ALEMBIC_ADOPT_EXISTING=1")
        expected = {column.name: column for column in columns if isinstance(column, sa.Column)}
        actual = {column["name"]: column for column in inspector.get_columns(name)}
        if set(expected) != set(actual) or any(not column.primary_key and column.nullable != actual[key]["nullable"] for key, column in expected.items()):
            raise RuntimeError("Existing table is incompatible with the frozen baseline: " + name)
        frozen = sa.Table(name, sa.MetaData(), *columns)
        for key, column in expected.items():
            reflected = actual[key]["type"]
            if column.type._type_affinity is not reflected._type_affinity:
                raise RuntimeError("Incompatible existing column type: " + name + "." + key)
            for attribute in ("length", "precision", "scale"):
                if getattr(column.type, attribute, None) != getattr(reflected, attribute, None):
                    raise RuntimeError("Incompatible existing column bounds: " + name + "." + key)
        if list(frozen.primary_key.columns.keys()) != inspector.get_pk_constraint(name)["constrained_columns"]:
            raise RuntimeError("Incompatible existing primary key: " + name)
        actual_foreign = {(tuple(c["constrained_columns"]), c["referred_table"], tuple(c["referred_columns"]),
                           c.get("options", {}).get("ondelete"), c.get("options", {}).get("onupdate"))
                          for c in inspector.get_foreign_keys(name)}
        # Resolve targets from strings; referenced tables may not be loaded yet.
        expected_foreign = {(tuple(c.columns.keys()), next(iter(c.elements)).target_fullname.split(".")[-2],
                             tuple(e.target_fullname.split(".")[-1] for e in c.elements), c.ondelete, c.onupdate)
                            for c in frozen.foreign_key_constraints}
        if expected_foreign != actual_foreign:
            raise RuntimeError("Incompatible existing foreign keys: " + name)
        expected_unique = {tuple(c.columns.keys()) for c in frozen.constraints if isinstance(c, sa.UniqueConstraint)}
        actual_unique = {tuple(c["column_names"]) for c in inspector.get_unique_constraints(name)}
        if not expected_unique.issubset(actual_unique):
            raise RuntimeError("Missing existing uniqueness constraint: " + name)
        return
    op.create_table(name, *columns, **kwargs)

def _create_index(name, table_name, columns, **kwargs):
    actual = {index["name"]: index for index in sa.inspect(op.get_bind()).get_indexes(table_name)}
    if name in actual:
        if actual[name]["column_names"] != columns or actual[name]["unique"] != bool(kwargs.get("unique", False)):
            raise RuntimeError("Incompatible existing index: " + name)
        return
    op.create_index(name, table_name, columns, **kwargs)

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    _create_table('demo_datasets',
    sa.Column('run_key', sa.String(length=80), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generator_version', sa.String(length=40), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('run_key')
    )
    _create_table('recipient_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=60), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'provider', 'kind', name='uq_recipient_service')
    )
    _create_index(op.f('ix_recipient_registrations_number'), 'recipient_registrations', ['number'], unique=False)
    _create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    _create_table('assistant_conversations',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('display_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('theme', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('notification_read_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_transaction_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('pay_later_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outstanding', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('pilot_participants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('variant', sa.String(length=10), nullable=False),
    sa.Column('verified_real', sa.Boolean(), nullable=False),
    sa.Column('consent_version', sa.String(length=30), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('savings_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('monthly_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('contribution_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_return', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('matures_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_savings_plans_user_id'), 'savings_plans', ['user_id'], unique=False)
    _create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('counterparty', sa.String(length=120), nullable=True),
    sa.Column('reference', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    _create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    _create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=40), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('photo_data', sa.LargeBinary(), nullable=True),
    sa.Column('photo_mime', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('wallet_opening_balances',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    _create_table('notification_read_receipts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'transaction_id')
    )
    _create_table('pay_later_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.String(length=100), nullable=False),
    sa.Column('invoice_no', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('purchase_transaction_id', sa.Integer(), nullable=False),
    sa.Column('repayment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repaid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchase_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['repayment_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('purchase_transaction_id'),
    sa.UniqueConstraint('repayment_transaction_id'),
    sa.UniqueConstraint('user_id', 'merchant', 'invoice_no', name='uq_pay_later_merchant_invoice')
    )
    _create_index(op.f('ix_pay_later_purchases_due_on'), 'pay_later_purchases', ['due_on'], unique=False)
    _create_index(op.f('ix_pay_later_purchases_user_id'), 'pay_later_purchases', ['user_id'], unique=False)
    _create_table('payment_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=90), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('account_reference', sa.String(length=60), nullable=False),
    sa.Column('invoice_reference', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('transaction_id'),
    sa.UniqueConstraint('user_id', 'category', 'provider', 'invoice_reference', name='uq_payment_invoice_reference')
    )
    _create_index(op.f('ix_payment_invoices_user_id'), 'payment_invoices', ['user_id'], unique=False)
    _create_table('payment_submissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'token')
    )
    _create_table('pilot_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('task_key', sa.String(length=30), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('task_token', sa.String(length=32), nullable=True),
    sa.Column('dedup_key', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pilot_participants.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dedup_key', name='uq_pilot_event_dedup')
    )
    _create_index(op.f('ix_pilot_events_created_at'), 'pilot_events', ['created_at'], unique=False)
    _create_index(op.f('ix_pilot_events_kind'), 'pilot_events', ['kind'], unique=False)
    _create_index(op.f('ix_pilot_events_task_token'), 'pilot_events', ['task_token'], unique=False)
    _create_index(op.f('ix_pilot_events_user_id'), 'pilot_events', ['user_id'], unique=False)
    _create_table('pilot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('problem', sa.String(length=30), nullable=False),
    sa.Column('usefulness', sa.Integer(), nullable=True),
    sa.Column('ease', sa.Integer(), nullable=True),
    sa.Column('missed_payments_last_30_days', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['pilot_participants.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    _create_index(op.f('ix_pilot_feedback_user_id'), 'pilot_feedback', ['user_id'], unique=False)
    _create_table('scheduled_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('recipient_number', sa.String(length=60), nullable=False),
    sa.Column('recipient_name', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('auto_pay', sa.Boolean(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('recurrence_group', sa.String(length=40), nullable=False),
    sa.Column('seed_key', sa.String(length=80), nullable=True),
    sa.Column('last_error', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_key'),
    sa.UniqueConstraint('transaction_id')
    )
    _create_index(op.f('ix_scheduled_payments_due_at'), 'scheduled_payments', ['due_at'], unique=False)
    _create_index(op.f('ix_scheduled_payments_status'), 'scheduled_payments', ['status'], unique=False)
    _create_index(op.f('ix_scheduled_payments_user_id'), 'scheduled_payments', ['user_id'], unique=False)
    _create_table('wallet_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'token', name='uq_wallet_submission_token')
    )
    _create_index(op.f('ix_wallet_submissions_user_id'), 'wallet_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Destructive downgrade disabled; restore a tested database backup instead.")
