"""Document code defaults, never read an account database or environment secrets."""
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.services.service_catalog import BILL_CATEGORIES, MOBILE_OPERATORS, RECHARGE_AMOUNTS
from app.services.wallet_catalog import DEMO_ATMS, DEMO_BANKS, CASH_OUT_RATES, BANK_TRANSFER_FEES, VISA_TRANSFER_RATE
from app.services.payment_plans_service import PAY_LATER_MERCHANTS
from app.services.validation import MOBILE_OPERATOR_PREFIXES


def generate():
    sections = [
        'UPAYX — DEMO DEFAULTS / ডেমো তথ্যের তালিকা',
        '=' * 72,
        'Source: code defaults only. This file does not export real user data.',
        'সব নম্বর, ব্যালেন্স, fraud flag ও provider তালিকা পরীক্ষার জন্য।',
        'No real bank, card, ATM, SMS, lending or savings integrations are connected.',
        '',
        '1. SYNTHETIC HOUSEHOLD RESET DATASET AND LOGIN',
        '-' * 72,
        'Main demo wallet: 01329097775',
        'Name: Demo Household',
        'Email: demo-7775@example.invalid',
        'Rebuild: python scripts/reset_demo_data.py --confirm --as-of 2026-10-02',
        'Existing local database is backed up to instance/backups before replacement.',
        'The active database loses all previous records; the recovery backup is retained.',
        'Inclusive Bangladesh dates: 2026-06-05 through 2026-10-02 (120 days).',
        '345 total transactions across 4 wallets; 208 belong to Demo Household.',
        'Independent household opening balance: BDT 12,450.00.',
        'Household closing balance at this as-of date: BDT 108,212.50.',
        'Cash ledger: opening + successful incoming - successful outgoing including fees.',
        'DemoDataset and WalletOpeningBalance persist provenance and opening anchors.',
        'These are realistic synthetic examples, never real upay customer records.',
        'Verified fixture: true (not live KYC verification)',
        'Default OTP: 123456 (configurable through DEMO_OTP; this is a demo)',
        'Recipient wallet: 01944000001 — Demo Recipient Ayesha',
        'Recipient opening balance when first created: BDT 1,000.00',
        'Reset recipient closing balance: BDT 22,300.00.',
        '01944000004 | Demo Sender Karim | opening 25,000.00 | closing 13,450.00',
        '01944000005 | Demo Landlord Rahman | opening 2,000.00 | closing 40,000.00',
        'All wallet transfers in reset history have equal opposite sender/receiver entries.',
        '',
        '2. RECEIVER / PROVIDER / FRAUD DIRECTORY',
        '-' * 72,
        '01944000002 | CASH_OUT | Demo Authorized Agent | REGISTERED | any provider',
        '01944000003 | MOBILE_RECHARGE | Demo Subscriber Rafi | REGISTERED | Banglalink (019 prefix)',
        '01944000099 | ANY | Demo Flagged Recipient | BLOCKED',
        '  Reason: Fraud flag supplied only as a demonstration fixture.',
        'DEMO-METER-1001 | BILL_PAYMENT | DESCO Electricity | Demo Household Electricity | REGISTERED',
        'DEMO-GAS-1001 | BILL_PAYMENT | Titas Gas | Demo Household Gas | REGISTERED',
        'DEMO-NET-1001 | BILL_PAYMENT | Demo Broadband | Demo Household Internet | REGISTERED',
        'DEMO-WATER-1001 | BILL_PAYMENT | Demo Water Utility | Demo Household Water | REGISTERED',
        'DEMO-BLOCKED-1001 | ANY | Demo Flagged Bill Account | BLOCKED',
        '  Reason: Demonstration blocked account.',
        'Unlisted recipients are not registered. Send Money requires a local wallet.',
        'Fraud flags are local fixtures; they are not real-world allegations.',
        '',
        '3. LEGACY STARTUP FIXTURES (ONLY WHEN CREATING A FRESH DATABASE)',
        '-' * 72,
        'MOBILE_RECHARGE | OUT | Grameenphone • 017XXXXXXXX | BDT 300.00',
        'SEND_MONEY | OUT | 018XXXXXXXX | BDT 500.00',
        'BILL_PAYMENT | OUT | DESCO | BDT 620.00',
        'ADD_MONEY | IN | Bank Account | BDT 2,000.00',
        'Reference pattern: DEMO-{first four kind characters}-{user id}',
        'Startup creates an initial BDT 12,450 wallet; imported examples do not alter it.',
        'These compatibility defaults are separate from the reconciled explicit reset.',
        '',
        '4. RECONCILED 120-DAY RESET HISTORY AND FUTURE INSTALLMENTS',
        '-' * 72,
        'Generator: household-ledger-v2. Reference: DEMO120-{as-of YYYYMMDD}-{day YYYYMMDD}-{sequence}.',
        'Daily shared groceries, food and commuting transfers cover every date.',
        'Monthly salary BDT 38,500; rent BDT 9,500; electricity, gas, internet and water bills.',
        'Periodic card funding/reimbursements; weekly mobile recharge and cash withdrawals.',
        'Cash-out fee: 1.50% of principal, deducted together with the amount.',
        '16 bill invoices and payment-submission receipts; 156 wallet submission receipts.',
        'All 18 project tables contain synthetic reset fixtures, including preferences and profiles.',
        '913 records total across all project tables; empty assistant history is intentional.',
        'Review examples: two BDT 100 recharges on 30 Sep at 19:00/19:03, then BDT 1,500 on 1 Oct.',
        'These review examples are successful synthetic receipts, not fraud allegations.',
        'Full as-of calendar day is included, stored as UTC and displayed UTC+06:00.',
        'Restart freezes existing DEMO120 data; it never rolls or adds another window.',
        'An explicit reset with another --as-of date is required to replace the window.',
        'Next calendar month day 5: DESCO / DEMO-METER-1001 / BDT 1,320 / monthly automatic.',
        'Second upcoming month day 5: same DESCO installment / BDT 1,320 / automatic.',
        'Next month day 12: Banglalink / 01944000003 / BDT 200 / one-time automatic.',
        'Next month day 20: 01944000001 / BDT 500 / one-time manual.',
        'Near-term manual DESCO bill: BDT 620 on 2026-10-05; no advance debit.',
        'Compatibility startup history: one imported transaction/day, rotating six basic types.',
        'Legacy imported history preserves balance and has no independent opening anchor.',
        'Plans move no balance until due and successfully executed.',
        '',
        '5. CASH OUT AND TRANSFER DEMO TERMS',
        '-' * 72,
        f'Agent cash out fee: {CASH_OUT_RATES["AGENT"] * 100}% of principal.',
        f'ATM cash out fee: {CASH_OUT_RATES["ATM"] * 100}% of principal.',
        'ATM amounts: multiples of BDT 500; maximum BDT 20,000.',
        'General operation amount: BDT 0.01–100,000 with two decimal places.',
        'Fee rounding: nearest paisa, ROUND_HALF_UP. Wallet debit = amount + fee.',
        f'NPSB bank transfer fee: BDT {BANK_TRANSFER_FEES["NPSB"]}.',
        f'BEFTN (BFTN alias) bank transfer fee: BDT {BANK_TRANSFER_FEES["BEFTN"]}.',
        f'Visa transfer fee: {VISA_TRANSFER_RATE * 100}%. Demo Visa: 4111111111111111.',
        'Demo bank account number: 1234567890. Visa numbers are masked in records.',
        'Add Money bank source: listed demo bank, 6-20 digit account number and holder name.',
        'Add Money card source: checksum-valid 13-19 digit demo card number and holder name.',
        'Sample funding card: 4111111111111111. Agent source requires its mobile number.',
        'Stored funding bank/card numbers retain only their last four digits.',
        'These are prototype terms, not live provider prices or settlement guarantees.',
        '',
        'ATM examples:',
        *[f'  {code} | {name}' for code, name in DEMO_ATMS.items()],
        '',
        'Bank examples:',
        *[f'  {index:02}. {name}' for index, name in enumerate(DEMO_BANKS, 1)],
        '',
        '6. SAVINGS AND PAY LATER',
        '-' * 72,
        'Savings: fixed monthly amount BDT 0.01–100,000; fixed tenure 1–120 months.',
        'Demo annual simple return: 10%. Beginning-of-month contributions.',
        'Principal = monthly amount × months.',
        'Estimated return = monthly amount × 0.10 × months × (months + 1) / 24.',
        'Example: BDT 100 monthly × 12 = BDT 1,200 principal + BDT 65 estimate.',
        'Maximum 10 active saved goals per user; save/archive does not move wallet funds.',
        'Savings records are estimates only. Compatibility startup seeds no savings plans.',
        'Explicit reset seeds Emergency fund (BDT 1,500 x 12) and Education fund (BDT 1,000 x 6).',
        'Pay Later demo limit: BDT 5,000 across all outstanding purchases.',
        'Tenure: 7, 14 or 30 Bangladesh calendar days. Demo interest and fees: 0%.',
        'Purchase status DEFERRED: no immediate wallet debit; receipt records the obligation.',
        'Manual repayment deducts wallet once and releases credit. No automatic late fees.',
        'Compatibility startup seeds no Pay Later purchases/accounts.',
        'Explicit reset: BDT 1,250 Bookshop purchase repaid; BDT 840 Pharmacy purchase pending.',
        'Reset credit exposure BDT 840; available credit BDT 4,160.',
        'Pending Pharmacy due date: 2026-10-06, seven-day tenure from 2026-09-29.',
        'Health reserve BDT 1,460; safe-to-spend estimate BDT 106,752.50 at reset date.',
        'Pay Later merchant examples:',
        *[f'  {index:02}. {name}' for index, name in enumerate(PAY_LATER_MERCHANTS, 1)],
        '',
        '7. MOBILE RECHARGE',
        '-' * 72,
        'Operators: ' + ', '.join(MOBILE_OPERATORS),
        'Demo operator checks use number prefixes; ported numbers are not resolved.',
        *[f'  {name}: ' + ', '.join(prefixes) for name, prefixes in MOBILE_OPERATOR_PREFIXES.items()],
        'Preset amounts (BDT): ' + ', '.join(str(value) for value in RECHARGE_AMOUNTS),
        '',
        '8. PAYMENT CATEGORY AND PROVIDER EXAMPLES',
        '-' * 72,
        'Provider names are offline examples. A name does not establish a partnership.',
        'Education is split into Education, School, College and University categories.',
        'Gas includes six natural-gas distributors, two LPG brands and two labeled demos.',
        'Each category contains 10 example options. Validate category/provider on server.',
    ]
    for slug, details in BILL_CATEGORIES.items():
        sections.extend(['', f'{details["label"]} [{slug}] — {details["account_label"]}'])
        sections.extend(f'  {index:02}. {provider}' for index, provider in enumerate(details['providers'], 1))
    sections.extend(['', '9. INVOICES, QR, NOTIFICATIONS AND DISPLAY DEFAULTS', '-' * 72,
                     'Transaction reference: generated UPX... identifier; invoice: INV-{UPX reference}.',
                     'Bill invoice reference: normalized uppercase; unique per user/category/provider.',
                     'Browser submission tokens prevent repeated form payments; reads move no funds.',
                     'QR: signed demo instructions, expires after 15 minutes; does not execute payment.',
                     'Bill/cash QR is owner-only. Money request QR can be scanned by another wallet.',
                     'Notifications enabled by default; individual and mark-all read state persist.',
                     'Default language: English (en). Other option: বাংলা (bn).',
                     'Default theme: System. Other options: Light and Dark.',
                     'Assistant: local scoped guide without an API key; optional configured hosted AI.',
                     'Provider key, live balances and private user data are never exported here.',
                     '', 'Sources:', 'app/services/demo_seed.py; app/__init__.py; config.py',
                     'app/services/service_catalog.py; app/services/wallet_catalog.py',
                     'app/services/payment_plans_service.py; app/services/qr_service.py',
                     'Regenerate: python scripts/generate_demo_reference.py', ''])
    destination = ROOT / 'DEMO_DATA.txt'
    destination.write_text('\n'.join(sections), encoding='utf-8')
    print(f'Wrote {destination.name}: {len(BILL_CATEGORIES)} categories, {sum(len(v["providers"]) for v in BILL_CATEGORIES.values())} provider options.')


if __name__ == '__main__':
    generate()
